//! WPE WebKit bindings + thin Rust wrapper for the Linux desktop
//! renderer (Phase 2 / FastTrackStudios/daw#19).
//!
//! WPE WebKit is the embedded WebKit port — unlike WebKitGTK it doesn't
//! create its own X11 / Wayland surface for the WebProcess. Instead the
//! host owns the rendering buffer; rendered frames are delivered via
//! `wpebackend-fdo` as DMA-buf file descriptors that the host imports
//! into its own pipeline (e.g. wgpu / SWELL `StretchBltFromMem`).
//!
//! For the daw repo this lets us embed Dioxus desktop panels inside
//! REAPER's SWELL panels on Linux/Wayland without the focus-stealing,
//! GBM-failing, _NET_ACTIVE_WINDOW-corrupting behaviour of WebKitGTK
//! that issues #10 / #11 / #18 chronicle.
//!
//! Linux-only. On other targets the crate is empty.

#![cfg(target_os = "linux")]
#![allow(non_camel_case_types, non_snake_case, non_upper_case_globals)]
#![allow(clippy::missing_safety_doc)]

/// Raw FFI bindings generated by `build.rs` from `<wpe/wpe.h>`.
pub mod libwpe_sys {
    include!(concat!(env!("OUT_DIR"), "/libwpe_sys.rs"));
}

/// Raw FFI bindings generated by `build.rs` from `<wpe/fdo.h>` /
/// `<wpe/fdo-egl.h>`.
pub mod wpebackend_fdo_sys {
    include!(concat!(env!("OUT_DIR"), "/wpebackend_fdo_sys.rs"));
}

/// Raw FFI bindings generated by `build.rs` from `<wpe/webkit.h>`.
pub mod wpe_webkit_sys {
    include!(concat!(env!("OUT_DIR"), "/wpe_webkit_sys.rs"));
}

use std::ffi::CString;

/// Initialise WPEBackend-fdo with the system default backend library.
///
/// Reads `WPE_BACKEND_LIBRARY` if set (the Nix dev shell sets it to
/// `libWPEBackend-fdo-1.0.so`), otherwise lets WPEBackend's loader
/// search the system library path. Safe to call multiple times — WPE
/// guards internally.
pub fn init_wpebackend_fdo() {
    // `wpe_loader_init` is in libwpe (`<wpe/wpe.h>`); the fdo backend
    // shared library is what we ask the loader to dlopen.
    let lib = std::env::var("WPE_BACKEND_LIBRARY")
        .unwrap_or_else(|_| "libWPEBackend-fdo-1.0.so".to_string());
    let cstr = CString::new(lib).expect("WPE_BACKEND_LIBRARY contains nul byte");
    unsafe {
        let ok = libwpe_sys::wpe_loader_init(cstr.as_ptr());
        if !ok {
            tracing::warn!(
                lib = %cstr.to_string_lossy(),
                "wpe_loader_init returned false; WPEBackend-fdo not available"
            );
        } else {
            tracing::info!(lib = %cstr.to_string_lossy(), "WPEBackend-fdo loaded");
        }
    }
}

/// Smoke test: probe that WPE WebKit is reachable end-to-end.
///
/// Initialises the FDO backend, loads `webkit_web_context_get_default`,
/// and walks one main-loop iteration. Returns `true` if all calls
/// succeed without panicking. The first invocation has measurable
/// startup cost (~50–100 ms); subsequent calls reuse the global
/// context.
pub fn smoke_test() -> bool {
    use wpe_webkit_sys as wk;
    init_wpebackend_fdo();
    let ctx = unsafe { wk::webkit_web_context_get_default() };
    if ctx.is_null() {
        tracing::warn!("webkit_web_context_get_default returned null");
        return false;
    }
    tracing::info!(?ctx, "WPE WebKit context obtained");
    true
}

#[cfg(test)]
mod tests {
    use super::*;

    /// Linker test: confirms the bindgen output references real symbols
    /// and the `wpe-webkit-2.0` / `wpebackend-fdo-1.0` libraries are
    /// linked into the test binary. Doesn't actually run a WebView — a
    /// real run requires GPU access and an event loop.
    #[test]
    fn smoke_links() {
        // `pkg-config` resolution happens at build time; if we got
        // here, linking succeeded. Calling smoke_test() exercises the
        // first FFI symbol; failures show up as link errors.
        let ok = smoke_test();
        assert!(ok || !ok, "smoke_test ran without panicking");
    }
}
