use dynamic_template::*;

#[test]
fn mars_sws() {
    // Track list from "Mars SWS"
    let items = vec![
        "Bass Synth.L.wav",
        "Bass Synth.R.wav",
        "Bass Synth.wav",
        "Bass Synth.wav",
        "Bass Synth.wav",
        "BGV1_SUM.wav",
        "BGV1_SUM.wav",
        "BGV1A.wav",
        "BGV1A.wav",
        "BGV1A.wav",
        "BGV1A.wav",
        "BGV1B.wav",
        "BGV1B.wav",
        "BGV1B.wav",
        "BGV1B.wav",
        "BGV1C.wav",
        "BGV1C.wav",
        "BGV1C.wav",
        "BGV1C.wav",
        "BGV1D.wav",
        "BGV1D.wav",
        "BGV1D.wav",
        "BGV1D.wav",
        "BGV2_SUM.wav",
        "BGV2_SUM.wav",
        "BGV2A.wav",
        "BGV2A.wav",
        "BGV2A.wav",
        "BGV2A.wav",
        "BGV2B.wav",
        "BGV2B.wav",
        "BGV2B.wav",
        "BGV2B.wav",
        "BGV2C.wav",
        "BGV2C.wav",
        "BGV2C.wav",
        "BGV2C.wav",
        "BGV2D.wav",
        "BGV2D.wav",
        "BGV2D.wav",
        "BGV2D.wav",
        "BGV3_SUM.wav",
        "BGV3_SUM.wav",
        "BGV3A.wav",
        "BGV3A.wav",
        "BGV3A.wav",
        "BGV3A.wav",
        "BGV3B.wav",
        "BGV3B.wav",
        "BGV3B.wav",
        "BGV3B.wav",
        "BGV3C.wav",
        "BGV3C.wav",
        "BGV3C.wav",
        "BGV3C.wav",
        "BGV3D.wav",
        "BGV3D.wav",
        "BGV3D.wav",
        "BGV3D.wav",
        "BGV4_SUM.wav",
        "BGV4_SUM.wav",
        "BGV4A.wav",
        "BGV4A.wav",
        "BGV4A.wav",
        "BGV4A.wav",
        "BGV4B.wav",
        "BGV4B.wav",
        "BGV4B.wav",
        "BGV4B.wav",
        "BGV4C.wav",
        "BGV4C.wav",
        "BGV4C.wav",
        "BGV4C.wav",
        "BGV4D.wav",
        "BGV4D.wav",
        "BGV4D.wav",
        "BGV4D.wav",
        "Crystalizer_Print_1.wav",
        "Crystalizer_Print.wav",
        "Crystalizer_Print.wav",
        "Kim VOX_1.wav",
        "Kim VOX_2.wav",
        "Kim VOX_2.wav",
        "Kim VOX_SUM.wav",
        "Kim VOX_SUM.wav",
        "Kim VOX.wav",
        "Kim VOX.wav",
        "Kim VOX.wav",
        "Mars Kim vx.wav",
        "Mars_PLAP.wav",
        "Piano L.wav",
        "Piano L.wav",
        "Piano L.wav",
        "Piano L.wav",
        "Piano R.wav",
        "Piano R.wav",
        "Piano R.wav",
        "Piano R.wav",
        "Piano Room Mono.wav",
        "Piano Room Mono.wav",
        "Piano Room Mono.wav",
        "Piano Room Mono.wav",
        "Piano_Rough_76bpm.wav",
        "Piano_SUM.wav",
        "Piano_SUM.wav",
        "Reverse Piano.wav",
        "Reverse Piano.wav",
        "Reverse Piano.wav",
        "Reverse Piano.wav",
        "Steve VOX_SUM.wav",
        "Steve VOX_SUM.wav",
        "Steve VOX.wav",
        "Steve VOX.wav",
        "Steve VOX.wav",
        "Steve VOX.wav",
    ];
    
    // Organize into tracks using monarchy sort
    let config = default_config();
    let tracks = items.organize_into_tracks(&config, None).unwrap();
    
    // Display the track list
    println!("\nTrack list:");
    daw::tracks::display_tracklist(&tracks);
    
    // TODO: Add expected structure once provided
}
