[application]
name = "Task"
default_platform = "web"

[web.app]
title = "Task"

[web.resource]
style = []
script = []

[web.resource.dev]
script = []

[bundle]
identifier = "com.codyswright.task.web"
publisher = "Cody Wright"
name = "Task"
