//! `architect` — one derive, one struct, every surface.
//!
//! Users write:
//!
//! ```ignore
//! #[derive(architect::Entity)]
//! #[architect(table_name = "examples", repo)]
//! pub struct Example {
//!     #[architect(primary_key, on_create = Uuid::new_v4())]
//!     pub id: Uuid,
//!     #[architect(filterable, sortable, fulltext)]
//!     pub name: String,
//! }
//! ```
//!
//! and get, from one definition:
//!
//! - The wasm-clean wire struct (with `facet::Facet` derived)
//! - `ExampleCreate` / `ExampleUpdate` / `ExampleList` payload types
//! - The `ExampleRepo` `#[vox::service]` trait (typed RPC for the wire)
//! - `ExampleClient` auto-generated by vox for browser / desktop / iOS
//! - With `--features server`, the full SeaORM `Model` + `Entity` +
//!   `Column` + `Relation` + `ActiveModel`, plus an
//!   `ExampleRepoStorage<C: ConnectionTrait>` that implements the repo
//!   trait against a SeaORM connection.
//!
//! Wire encoding is **facet-only**. Vox already speaks facet on its
//! transport layer, so architect types travel as a coherent system
//! with zero per-type serde glue.

pub use architect_derive::Entity;

// Re-export facet unconditionally — every architect-emitted struct
// uses it for wire encoding regardless of whether RPC is in play.
pub use facet;

// Vox re-export only when the `vox` feature is on. Consumers that
// want in-process trait use (no dispatcher, no client, no RPC at all)
// can disable the vox feature on their proto crate to drop the
// dependency entirely.
#[cfg(feature = "vox")]
pub use vox;

// fake-rs re-export, gated on the `fake` feature. Lets consumers reach
// `architect::fake::{Dummy, Faker, Fake}` without a direct dep.
#[cfg(feature = "fake")]
pub use fake;

// ── Repository error envelope ──────────────────────────────────────────

/// Error returned by every architect-generated repo method. Tight on
/// purpose — new variants are a wire-format change for every existing
/// `<Entity>Repo` trait.
#[derive(Debug, Clone, PartialEq, Eq, facet::Facet, thiserror::Error)]
#[repr(u8)]
pub enum RepoError {
    #[error("entity not found")]
    NotFound,
    #[error("invalid input: {0}")]
    InvalidInput(String),
    #[error("conflict: {0}")]
    Conflict(String),
    #[error("internal error: {0}")]
    Internal(String),
}

// ── Pagination + sort + filter primitives (wire-safe) ──────────────────

#[cfg_attr(feature = "fake", derive(fake::Dummy))]
#[derive(Debug, Clone, PartialEq, Eq, facet::Facet, Default)]
pub struct Page {
    /// Zero-indexed page number.
    pub index: u32,
    /// Items per page. Implementations clamp to a sane max.
    pub size: u32,
}

#[cfg_attr(feature = "fake", derive(fake::Dummy))]
#[derive(Debug, Clone, Copy, PartialEq, Eq, facet::Facet)]
#[repr(u8)]
pub enum SortOrder {
    Asc,
    Desc,
}

#[cfg_attr(feature = "fake", derive(fake::Dummy))]
#[derive(Debug, Clone, PartialEq, Eq, facet::Facet)]
pub struct Sort {
    /// Field name (matches the API struct's snake_case identifier).
    pub field: String,
    pub order: SortOrder,
}

/// Free-form filter expression. Parsed server-side from a JSON-shaped
/// string for now; an evolving structured form lands as the macro
/// grows.
#[cfg_attr(feature = "fake", derive(fake::Dummy))]
#[derive(Debug, Clone, PartialEq, Eq, facet::Facet, Default)]
pub struct Filter {
    pub raw: String,
}

// ── Storage trait (server-only) ────────────────────────────────────────
//
// The macro-generated `<Entity>RepoStorage<C>` parameterizes over a
// SeaORM connection and implements the `<Entity>Repo` vox trait. The
// glue is mechanical; this trait lets architect's emitted impl call
// into SeaORM through a stable API.

#[cfg(feature = "server-axum")]
pub mod axum_ws;

#[cfg(feature = "fake")]
pub mod seed {
    //! Helpers for the architect-emitted `seed_fake_<entity>` functions.
    //!
    //! Each entity that opts into `fake` gets a `pub async fn
    //! seed_fake_<snake>(repo, count)` in its proto crate. The `count`
    //! argument takes anything that implements [`SeedCount`] — a
    //! single number (`500`), a `Range<usize>` (`10..30` — picks a
    //! random count in that range each call), or any other shape you
    //! impl the trait for.

    use std::ops::{Range, RangeInclusive};

    /// "How many faked rows do you want?" — implemented for the obvious
    /// integer types and ranges.
    pub trait SeedCount {
        fn pick(&self) -> usize;
    }

    impl SeedCount for usize {
        fn pick(&self) -> usize {
            *self
        }
    }
    impl SeedCount for u32 {
        fn pick(&self) -> usize {
            *self as usize
        }
    }
    impl SeedCount for u64 {
        fn pick(&self) -> usize {
            *self as usize
        }
    }
    impl SeedCount for i32 {
        fn pick(&self) -> usize {
            (*self).max(0) as usize
        }
    }

    impl SeedCount for Range<usize> {
        fn pick(&self) -> usize {
            use fake::rand::Rng;
            if self.is_empty() {
                return self.start;
            }
            fake::rand::rng().random_range(self.start..self.end)
        }
    }
    impl SeedCount for Range<u32> {
        fn pick(&self) -> usize {
            (self.start as usize..self.end as usize).pick()
        }
    }
    impl SeedCount for RangeInclusive<usize> {
        fn pick(&self) -> usize {
            use fake::rand::Rng;
            fake::rand::rng().random_range(*self.start()..=*self.end())
        }
    }
    impl SeedCount for RangeInclusive<u32> {
        fn pick(&self) -> usize {
            (*self.start() as usize..=*self.end() as usize).pick()
        }
    }
}

#[cfg(feature = "server-seaorm")]
pub mod storage {
    //! Generic storage helpers used by macro-emitted code.

    use sea_orm::ConnectionTrait;

    /// Bound the macro's emitted repository structs use for their
    /// connection generic. Kept here so the macro doesn't have to
    /// emit the long trait list at every callsite.
    pub trait DbConn: ConnectionTrait + Clone + Send + Sync + 'static {}

    impl<T> DbConn for T where T: ConnectionTrait + Clone + Send + Sync + 'static {}
}
