//! `architect` — one derive, one struct, every surface.
//!
//! Users write:
//!
//! ```ignore
//! #[derive(architect::Entity)]
//! #[architect(table_name = "examples", repo)]
//! pub struct Example {
//!     #[architect(primary_key, on_create = Uuid::new_v4())]
//!     pub id: Uuid,
//!     #[architect(filterable, sortable, fulltext)]
//!     pub name: String,
//! }
//! ```
//!
//! and get, from one definition:
//!
//! - The wasm-clean wire struct (with `facet::Facet` derived)
//! - `ExampleCreate` / `ExampleUpdate` / `ExampleList` payload types
//! - The `ExampleRepo` `#[vox::service]` trait (typed RPC for the wire)
//! - `ExampleClient` auto-generated by vox for browser / desktop / iOS
//! - With `--features server`, the full SeaORM `Model` + `Entity` +
//!   `Column` + `Relation` + `ActiveModel`, plus an
//!   `ExampleRepoStorage<C: ConnectionTrait>` that implements the repo
//!   trait against a SeaORM connection.
//!
//! Wire encoding is **facet-only**. Vox already speaks facet on its
//! transport layer, so architect types travel as a coherent system
//! with zero per-type serde glue.

pub use architect_derive::Entity;

// Companion derive for any type carried by an `#[architect(json)]`
// field. Emits the four sea_orm traits (`Into<Value>`, `TryGetable`,
// `ValueType`, `Nullable`) via a `serde_json` round-trip, cfg-gated
// on the user's `server` feature. See the derive's docs in
// `architect-derive` for the Vec<T> newtype pattern.
pub use architect_derive::JsonField;

// `#[architect::rpc]` attribute macro — turns a sync (or mixed) trait
// into a sync API + async vox client + server-side host. See
// `DESIGN.md` and the `dispatch` module for the runtime contract the
// emitted code relies on.
pub use architect_rpc_derive::rpc;

// Re-export facet unconditionally — every architect-emitted struct
// uses it for wire encoding regardless of whether RPC is in play.
pub use facet;

// Vox re-export only when the `vox` feature is on. Consumers that
// want in-process trait use (no dispatcher, no client, no RPC at all)
// can disable the vox feature on their proto crate to drop the
// dependency entirely.
#[cfg(feature = "vox")]
pub use vox;

// Effect-style service composition. `Layer` + `layers!` let callers
// bundle architect-rpc services into a single value and mount them as
// a unit via `.provide(backend)`. See [`layer`] module docs.
#[cfg(feature = "vox")]
pub mod layer;
#[cfg(feature = "vox")]
pub use layer::{
    Append, Bind, BindAny, Cons, Descriptors, Empty, Layer, LayerRouter, LayerSink, Mounted,
    Services,
};

// Construction layer — lazy backend builders with dependent composition,
// memoization, and scoped (LIFO) teardown. Feeds the service layer's
// `.provide()` via `Resource::into_router` (vox-gated inside). The
// `Scope`/`Resource` surface itself is transport-agnostic.
pub mod resource;
pub use resource::{Resource, Scope, SharedResource};

// Dependency planner — topologically order a declared layer graph, with
// cycle / conflict / missing-provider diagnostics. Pure data.
pub mod plan;
pub use plan::{LayerDiagnostic, LayerGraph, LayerNode, LayerPlan, LayerPlanError};

// In-process transport — serve a `LayerRouter` over a vox in-memory link
// so a typed client consumes a local backend with no server. Native only
// (vox's `MemoryLink` isn't compiled for wasm).
#[cfg(all(feature = "local", not(target_arch = "wasm32")))]
pub mod local;
#[cfg(all(feature = "local", not(target_arch = "wasm32")))]
pub use local::{LocalServer, serve_local};

// fake-rs re-export, gated on the `fake` feature. Lets consumers reach
// `architect::fake::{Dummy, Faker, Fake}` without a direct dep.
#[cfg(feature = "fake")]
pub use fake;

// ── Repository error envelope ──────────────────────────────────────────

/// Error returned by every architect-generated repo method. Tight on
/// purpose — new variants are a wire-format change for every existing
/// `<Entity>Repo` trait.
#[derive(Debug, Clone, PartialEq, Eq, facet::Facet, thiserror::Error)]
#[repr(u8)]
pub enum RepoError {
    #[error("entity not found")]
    NotFound,
    #[error("invalid input: {0}")]
    InvalidInput(String),
    #[error("conflict: {0}")]
    Conflict(String),
    #[error("internal error: {0}")]
    Internal(String),
}

// ── Pagination + sort + filter primitives (wire-safe) ──────────────────

#[cfg_attr(feature = "fake", derive(fake::Dummy))]
#[derive(Debug, Clone, PartialEq, Eq, facet::Facet, Default)]
pub struct Page {
    /// Zero-indexed page number.
    pub index: u32,
    /// Items per page. Implementations clamp to a sane max.
    pub size: u32,
}

#[cfg_attr(feature = "fake", derive(fake::Dummy))]
#[derive(Debug, Clone, Copy, PartialEq, Eq, facet::Facet)]
#[repr(u8)]
pub enum SortOrder {
    Asc,
    Desc,
}

#[cfg_attr(feature = "fake", derive(fake::Dummy))]
#[derive(Debug, Clone, PartialEq, Eq, facet::Facet)]
pub struct Sort {
    /// Field name (matches the API struct's snake_case identifier).
    pub field: String,
    pub order: SortOrder,
}

/// Free-form filter expression. Parsed server-side from a JSON-shaped
/// string for now; an evolving structured form lands as the macro
/// grows.
#[cfg_attr(feature = "fake", derive(fake::Dummy))]
#[derive(Debug, Clone, PartialEq, Eq, facet::Facet, Default)]
pub struct Filter {
    pub raw: String,
}

// ── Storage trait (server-only) ────────────────────────────────────────
//
// The macro-generated `<Entity>RepoStorage<C>` parameterizes over a
// SeaORM connection and implements the `<Entity>Repo` vox trait. The
// glue is mechanical; this trait lets architect's emitted impl call
// into SeaORM through a stable API.

#[cfg(feature = "server-axum")]
pub mod axum_ws;

#[cfg(feature = "fake")]
pub mod seed {
    //! Helpers for the architect-emitted `seed_fake_<entity>` functions.
    //!
    //! Each entity that opts into `fake` gets a `pub async fn
    //! seed_fake_<snake>(repo, count)` in its proto crate. The `count`
    //! argument takes anything that implements [`SeedCount`] — a
    //! single number (`500`), a `Range<usize>` (`10..30` — picks a
    //! random count in that range each call), or any other shape you
    //! impl the trait for.

    use std::ops::{Range, RangeInclusive};

    /// "How many faked rows do you want?" — implemented for the obvious
    /// integer types and ranges.
    pub trait SeedCount {
        fn pick(&self) -> usize;
    }

    impl SeedCount for usize {
        fn pick(&self) -> usize {
            *self
        }
    }
    impl SeedCount for u32 {
        fn pick(&self) -> usize {
            *self as usize
        }
    }
    impl SeedCount for u64 {
        fn pick(&self) -> usize {
            *self as usize
        }
    }
    impl SeedCount for i32 {
        fn pick(&self) -> usize {
            (*self).max(0) as usize
        }
    }

    impl SeedCount for Range<usize> {
        fn pick(&self) -> usize {
            use fake::rand::Rng;
            if self.is_empty() {
                return self.start;
            }
            fake::rand::rng().random_range(self.start..self.end)
        }
    }
    impl SeedCount for Range<u32> {
        fn pick(&self) -> usize {
            (self.start as usize..self.end as usize).pick()
        }
    }
    impl SeedCount for RangeInclusive<usize> {
        fn pick(&self) -> usize {
            use fake::rand::Rng;
            fake::rand::rng().random_range(*self.start()..=*self.end())
        }
    }
    impl SeedCount for RangeInclusive<u32> {
        fn pick(&self) -> usize {
            (*self.start() as usize..=*self.end() as usize).pick()
        }
    }
}

// ── Dispatcher trait (used by #[architect::rpc] bridges) ───────────────
//
// `Dispatcher` is the marshaling primitive that runs a sync closure on
// the right thread / executor and produces a future for its result. The
// trait is intentionally object-safe (`Pin<Box<dyn Future>>` return) so
// architect-rpc-emitted host types can store `Arc<dyn Dispatcher>` and
// compose runtimes at runtime.
//
// Concrete impls live downstream (one per runtime context). Three are
// shipped in this crate as zero-cost helpers; more exotic ones (the
// REAPER main-thread queue, custom AudioWorklet bridges, etc.) live in
// the consumers that need them.

/// Backends that ship their own dispatcher.
///
/// Implementing this lets the macro-emitted `serve(backend)` function
/// pull the runtime-appropriate dispatcher straight off the backend
/// type — no explicit dispatcher argument at the mount site. The
/// dispatcher is part of the backend's identity: a REAPER backend
/// always wants REAPER's main-thread queue, a standalone backend
/// always wants the current-thread dispatcher, etc.
///
/// Tests or alternate-runtime scenarios that want a different
/// dispatcher for the same backend type use a newtype wrapper with
/// its own `HasDispatcher` impl.
pub trait HasDispatcher {
    /// The dispatcher type this backend uses. Construction must be
    /// free of side effects — `serve` calls this once per mount.
    type Dispatcher: dispatch::Dispatcher;

    /// Construct the dispatcher. Called once at mount time.
    fn dispatcher(&self) -> Self::Dispatcher;
}

pub mod dispatch {
    //! Marshaling primitive for `#[architect::rpc]` bridges.
    //!
    //! See [`Dispatcher`] for the contract. Consumers typically pick a
    //! pre-built dispatcher per binary — `tokio` server binaries reach
    //! for `TokioBlockingDispatcher` (gated on the `dispatch-tokio`
    //! feature); tests and pure in-process callers reach for
    //! [`CurrentThreadDispatcher`];
    //! runtime-specific dispatchers (moiré main-thread queue, REAPER
    //! defer queue) live in their own crates.

    use core::future::Future;
    use core::pin::Pin;

    /// Errors produced by a [`Dispatcher`]. These wrap "transport-level"
    /// failures around the user's closure — the closure shutdown, the
    /// runtime tear-down, a panic inside the worker. Application-level
    /// errors returned from the closure flow through the future's
    /// `Output` unchanged.
    #[derive(Debug, Clone, PartialEq, Eq, facet::Facet, thiserror::Error)]
    #[repr(u8)]
    pub enum DispatchError {
        /// The dispatcher has been shut down and cannot accept work.
        #[error("dispatcher has shut down")]
        ShutDown,
        /// The worker that ran the closure panicked. The string is the
        /// formatted panic payload when recoverable, or a generic
        /// description when not.
        #[error("worker panicked: {0}")]
        Panicked(String),
        /// The closure was cancelled before producing a result. Used by
        /// dispatchers that support deadlines or cooperative cancellation.
        #[error("dispatch cancelled")]
        Cancelled,
    }

    /// Marshals a sync closure onto a runtime-appropriate execution
    /// context and returns a future for its result.
    ///
    /// Object-safe by design: bridges store `Arc<dyn Dispatcher>` so the
    /// dispatcher choice is composable at runtime. The boxed-future
    /// return is one allocation per call, dwarfed by the dispatcher's
    /// own thread-hop cost.
    pub trait Dispatcher: Send + Sync + 'static {
        /// Run `f` on the dispatcher's execution context. The returned
        /// future resolves to the closure's value (wrapped in `Ok`) or
        /// a [`DispatchError`] describing why the closure never ran or
        /// never completed.
        fn dispatch(
            &self,
            f: Box<dyn FnOnce() -> BoxedAny + Send + 'static>,
        ) -> Pin<Box<dyn Future<Output = Result<BoxedAny, DispatchError>> + Send + 'static>>;
    }

    /// Opaque type carrying the closure's return value across the
    /// dispatcher boundary. Bridges downcast back to the concrete type
    /// they sent in; the type-erasure keeps `Dispatcher` object-safe
    /// without making it generic.
    pub type BoxedAny = Box<dyn core::any::Any + Send + 'static>;

    /// Convenience: run a typed closure through any `Dispatcher` and
    /// recover the typed result. This is the API bridge code generated
    /// by `#[architect::rpc]` actually calls — the trait method's
    /// `BoxedAny` shape stays a framework-internal detail.
    pub async fn run<D, F, T>(dispatcher: &D, f: F) -> Result<T, DispatchError>
    where
        D: Dispatcher + ?Sized,
        F: FnOnce() -> T + Send + 'static,
        T: Send + 'static,
    {
        let boxed: Box<dyn FnOnce() -> BoxedAny + Send + 'static> =
            Box::new(move || Box::new(f()) as BoxedAny);
        let any = dispatcher.dispatch(boxed).await?;
        Ok(*any
            .downcast::<T>()
            .expect("dispatcher must not alter the closure's return type"))
    }

    // ── Standard dispatcher: current-thread (call inline) ──────────────

    /// Calls the closure inline on the current thread. The returned
    /// future is always `Poll::Ready(Ok(_))` — no scheduling, no thread
    /// hop. Right for tests, single-threaded contexts, and in-process
    /// callers where there's no thread to marshal to.
    #[derive(Debug, Default, Clone, Copy)]
    pub struct CurrentThreadDispatcher;

    impl Dispatcher for CurrentThreadDispatcher {
        fn dispatch(
            &self,
            f: Box<dyn FnOnce() -> BoxedAny + Send + 'static>,
        ) -> Pin<Box<dyn Future<Output = Result<BoxedAny, DispatchError>> + Send + 'static>>
        {
            let result = f();
            Box::pin(async move { Ok(result) })
        }
    }

    // ── Standard dispatcher: tokio spawn_blocking ──────────────────────

    /// Marshals the closure onto a tokio blocking thread via
    /// [`tokio::task::spawn_blocking`]. Right for server-side binaries
    /// that wrap sync-shaped backends (a sync DB driver, a CPU-bound
    /// transform) inside an async service.
    ///
    /// Requires the `tokio` cargo feature; pulls `tokio` with the
    /// `rt` capability so `spawn_blocking` is available.
    #[cfg(feature = "dispatch-tokio")]
    #[derive(Debug, Default, Clone, Copy)]
    pub struct TokioBlockingDispatcher;

    #[cfg(feature = "dispatch-tokio")]
    impl Dispatcher for TokioBlockingDispatcher {
        fn dispatch(
            &self,
            f: Box<dyn FnOnce() -> BoxedAny + Send + 'static>,
        ) -> Pin<Box<dyn Future<Output = Result<BoxedAny, DispatchError>> + Send + 'static>>
        {
            Box::pin(async move {
                tokio::task::spawn_blocking(f).await.map_err(|join_err| {
                    if join_err.is_panic() {
                        DispatchError::Panicked(format!("{join_err:?}"))
                    } else {
                        DispatchError::Cancelled
                    }
                })
            })
        }
    }

    #[cfg(test)]
    mod tests {
        use super::*;

        #[test]
        fn current_thread_runs_inline_and_returns_value() {
            let d = CurrentThreadDispatcher;
            // `run` is async; resolve the future synchronously since
            // CurrentThreadDispatcher never actually defers.
            let fut = run(&d, || 1u32 + 2);
            let result = futures_lite::future::block_on(fut).unwrap();
            assert_eq!(result, 3);
        }

        #[test]
        fn current_thread_passes_owned_data_through() {
            let d = CurrentThreadDispatcher;
            let payload = vec!["a".to_string(), "b".to_string()];
            let payload_clone = payload.clone();
            let fut = run(&d, move || payload_clone);
            let result = futures_lite::future::block_on(fut).unwrap();
            assert_eq!(result, payload);
        }
    }
}

#[cfg(feature = "server-seaorm")]
pub mod storage {
    //! Generic storage helpers used by macro-emitted code.

    use sea_orm::ConnectionTrait;

    /// Bound the macro's emitted repository structs use for their
    /// connection generic. Kept here so the macro doesn't have to
    /// emit the long trait list at every callsite.
    pub trait DbConn: ConnectionTrait + Clone + Send + Sync + 'static {}

    impl<T> DbConn for T where T: ConnectionTrait + Clone + Send + Sync + 'static {}
}
