[application]
name = "KeyflowPlayground"

[desktop]
title = "Keyflow Playground"

[web.app]
title = "Keyflow Playground"

[web.resource]
style = []
script = []

[web.resource.dev]
script = []

[bundle]
identifier = "com.fasttrackstudio.keyflow-playground"
publisher = "FastTrack Studio"
name = "Keyflow Playground"
