[package]
name = "playground-wasm"
version = "0.1.0"
edition = "2024"

[dependencies]
dioxus = { version = "0.7.2", features = ["router"] }
daw = { workspace = true, features = ["standalone-rpp"] }
tracing = "0.1"
wasm-bindgen = "0.2"
wasm-bindgen-futures = "0.4"
web-time = "1"

[target.'cfg(target_arch = "wasm32")'.dependencies]
tracing-wasm = "0.2"
gloo-timers = { version = "0.3", features = ["futures"] }
js-sys = "0.3"
web-sys = { version = "0.3", features = [
    "Window",
    "Document",
    "HtmlElement",
    "Performance",
    "File",
    "FileList",
    "FileReader",
    "Blob",
    "HtmlInputElement",
    "Event",
    "DragEvent",
    "DataTransfer",
] }

[target.'cfg(not(target_arch = "wasm32"))'.dependencies]
tokio = { workspace = true }

[dev-dependencies]
wasm-bindgen-test = "0.3"

[features]
default = ["web"]
web = ["dioxus/web"]
