// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Orchestral brass instruments
 */
export type BrassInstrument = "Horn" | "Trumpet" | "Trombone" | "BassTrombone" | "Tuba";
