// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Guitar family instruments
 */
export type GuitarInstrument = "AcousticGuitar" | "ElectricGuitar" | "ClassicalGuitar" | "BassGuitar" | "ElectricBass" | "Banjo" | "Mandolin" | "Ukulele" | "TwelveString" | "SteelGuitar";
