// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Harp instrument (separate from bowed strings due to unique characteristics)
 */
export type HarpInstrument = "Harp" | "CelticHarp" | "ElectricHarp";
