// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { BrassInstrument } from "./BrassInstrument";
import type { GuitarInstrument } from "./GuitarInstrument";
import type { HarpInstrument } from "./HarpInstrument";
import type { KeyboardInstrument } from "./KeyboardInstrument";
import type { PercussionInstrument } from "./PercussionInstrument";
import type { StringInstrument } from "./StringInstrument";
import type { Transposition } from "./Transposition";
import type { WoodwindInstrument } from "./WoodwindInstrument";
import type { WorldInstrument } from "./WorldInstrument";

/**
 * Main instrument enum encompassing all instrument types
 */
export type Instrument = { "String": StringInstrument } | { "Woodwind": [WoodwindInstrument, Transposition] } | { "Brass": [BrassInstrument, Transposition] } | { "Percussion": PercussionInstrument } | { "Keyboard": KeyboardInstrument } | { "Harp": HarpInstrument } | { "Guitar": GuitarInstrument } | { "World": WorldInstrument } | { "Other": string };
