// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Instrument categories for organization and color coding
 */
export type InstrumentCategory = "Strings" | "Woodwinds" | "Brass" | "Percussion" | "Keyboard" | "Harp" | "RhythmSection" | "Choir" | "Solo" | "World" | "Other";
