// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Keyboard instruments
 */
export type KeyboardInstrument = "Piano" | "ElectricPiano" | "Organ" | "PipeOrgan" | "Synthesizer" | "Harpsichord" | "Clavichord" | "Celesta" | "Keyboard" | "Workstation" | "Accordion" | "Harmonium";
