// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Instrument } from "./Instrument";
import type { Vocal } from "./Vocal";

/**
 * Musical part representation
 */
export type Part = { "Instrument": [Instrument, number | null] } | { "Solo": Instrument } | { "Vocal": Vocal } | "FullScore" | "ScoreAndParts" | { "Other": string };
