// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Band/popular percussion instruments
 */
export type PercussionInstrument = "DrumSet" | "SnareDrum" | "BassDrum" | "TomToms" | "HiHat" | "Ride" | "Crash" | "Splash" | "China" | "Timpani" | "ConcertBassDrum" | "ConcertSnareDrum" | "Glockenspiel" | "Vibraphone" | "Marimba" | "Xylophone" | "TubularBells" | "Crotales" | "Congas" | "Bongos" | "Timbales" | "Cowbell" | "Claves" | "Maracas" | "Guiro" | "Cabasa" | "TaikoDrums" | "Gong" | "TamTam" | "Tambourine" | "Triangle" | "Woodblock" | "TempleBlocks" | "SleighBells" | "WindChimes" | "FingerCymbals" | "Castanets" | "Whip" | "Ratchet" | "Thundersheet" | "ElectronicPad" | "DrumMachine" | "Percussion" | { "Other": string };
