// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Orchestral string instruments (bowed strings)
 */
export type StringInstrument = "Violin" | "Viola" | "Cello" | "DoubleBass";
