// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Common transpositions for transposing instruments
 */
export type Transposition = "C" | "Bb" | "A" | "F" | "Eb";
