// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Musical tuning/transposition for instruments using keyflow primitives
 */
export type Tuning = { 
/**
 * The root note of the tuning
 */
root: string, 
/**
 * The interval from concert pitch (C)
 */
interval_semitones: number, };
