// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Vocal parts and voice types
 */
export type Vocal = "Soprano" | "MezzoSoprano" | "Alto" | "Countertenor" | "Tenor" | "Baritone" | "Bass" | "Choir" | "ChildrensChoir" | "WomensChoir" | "MensChoir" | "Soloist";
