// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Orchestral woodwind instruments with transposition support
 */
export type WoodwindInstrument = "Piccolo" | "Flute" | "Oboe" | "EnglishHorn" | "Clarinet" | "BassClarinet" | "Bassoon" | "Contrabassoon";
