// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * World and ethnic instruments from various cultures
 */
export type WorldInstrument = "Erhu" | "Guzheng" | "Shakuhachi" | "Shamisen" | "Koto" | "TaikoDrum" | "Sitar" | "Tabla" | "Sarod" | "Tanpura" | "Bansuri" | "Oud" | "Duduk" | "Ney" | "Darbuka" | "Qanun" | "FrameDrum" | "CelticFiddle" | "Bagpipes" | "TinWhistle" | "Bodhran" | "CelticHarp" | "IrishFlute" | "UilleanPipes" | "Djembe" | "Kalimba" | "TalkingDrum" | "Balafon" | "Kora" | "Cajon" | "Maracas" | "Claves" | "Panpipes" | "Charango" | "Quena" | "CajonPeruano" | "Accordion" | "Concertina" | "Dulcimer" | "HurdyGurdy" | "AlpineZither" | "WorldPercussion" | "Other";
