[package]
name = "cell-runtime"
version = "0.1.0"
edition = "2024"

[features]
default = []
cell-debug = []

[dependencies]
cell-host-proto = { path = "../../cells/cell-host/cell-host-proto" }
roam = { workspace = true }
roam-shm = { workspace = true }
roam-tracing = { workspace = true }
tokio = { workspace = true }
tracing = { workspace = true }
tracing-subscriber = { workspace = true, features = ["env-filter"] }
ur-taking-me-with-you = { workspace = true }

[target.'cfg(unix)'.dependencies]
libc = "0.2"
