//! TransportService - Roam RPC service for transport control
//!
//! This module defines the `TransportService` trait using roam's `#[service]` macro.
//! Service implementations (`ReaperTransport`, `MockTransport`) provide the actual
//! execution logic.

use facet::Facet;
use roam::{Tx, prelude::*};

use super::core::transport::{PlayState, RecordMode, Tempo};
use crate::Transport;

// region:    --- Types

/// Command to execute on the transport
#[repr(u8)]
#[derive(Debug, Clone, Facet)]
pub enum TransportCommand {
    Play,
    Pause,
    Stop,
    PlayPause,
    PlayStop,
    Record,
    StopRecording,
    ToggleRecording,
    SetTempo(f64),
    SetPosition(f64),
    SetRecordMode(RecordMode),
    ToggleLoop,
}

/// Event emitted when transport state changes
#[repr(u8)]
#[derive(Debug, Clone, Facet)]
pub enum TransportEvent {
    /// Full state changed
    StateChanged(Transport),
    /// Play state changed
    PlayStateChanged(PlayState),
    /// Position changed (emitted frequently during playback)
    PositionChanged(f64),
    /// Tempo changed
    TempoChanged(Tempo),
    /// Record mode changed
    RecordModeChanged(RecordMode),
    /// Loop state changed
    LoopChanged(bool),
}

// endregion: --- Types

// region:    --- Service Trait

/// Transport service for controlling DAW transport.
///
/// This trait is generated by roam's `#[service]` macro and defines the RPC interface
/// for transport control. Implementations include:
/// - `ReaperTransport`: Real implementation that calls REAPER APIs
/// - `MockTransport`: Mock implementation for testing
#[roam::service]
pub trait TransportService {
    /// Get the current transport state
    async fn get_state(&self) -> Transport;

    /// Execute a transport command
    async fn execute(&self, cmd: TransportCommand);

    /// Subscribe to transport state changes
    ///
    /// Events are pushed to the provided channel whenever state changes.
    async fn subscribe(&self, events: Tx<TransportEvent>);

    /// Subscribe to position updates only (~30Hz during playback)
    ///
    /// This is a high-frequency stream optimized for playhead position.
    async fn subscribe_position(&self, positions: Tx<f64>);

    /// Get current play state
    async fn get_play_state(&self) -> PlayState;

    /// Get current tempo
    async fn get_tempo(&self) -> Tempo;

    /// Get current position in seconds
    async fn get_position(&self) -> f64;

    /// Check if currently playing
    async fn is_playing(&self) -> bool;

    /// Check if currently recording
    async fn is_recording(&self) -> bool;
}

// endregion: --- Service Trait
