[package]
name = "daw-reaper"
version.workspace = true
edition.workspace = true

[lib]
name = "daw_reaper"
path = "src/lib.rs"

[dependencies]
daw-proto = { path = "../daw-proto" }
extension-runtime = { path = "../../../modules/extension-runtime" }
reaper-medium = { workspace = true }
tokio = { workspace = true }
tracing = { workspace = true }
