//! Database seeding — populates the DB with FTS-Guitar default data on first launch.
//!
//! Uses explicit `ActiveModel` inserts (not the repo layer) to preserve the
//! cross-referenced UUIDs generated by the domain defaults.

use chrono::Utc;
use sea_orm::{ActiveModelTrait, DatabaseConnection, Set};

use signal_proto::block::Block;
use signal_proto::defaults::blocks::dummy;
use signal_proto::defaults::guitar::{build_guitar_rig, GuitarRigDefaults};
use signal_proto::defaults::modules::dummy as module_dummy;
use signal_proto::module_preset::{ModulePreset, ModuleSnapshot as DomainModuleSnapshot};
use signal_proto::performance::{PerformanceSong, Scene};
use signal_proto::preset::{Preset, Snapshot};
use signal_proto::profile::{PresetReference, Profile, SceneTemplate};

use crate::entities::{
    module_preset_entity, module_snapshot, performance_song, preset as preset_entity,
    profile as profile_entity, scene_template, snapshot as snapshot_entity, song_scene,
};
use crate::error::StorageResult;
use crate::facet_bridge;

/// Seed the database with FTS-Guitar defaults if it's empty.
///
/// Uses incremental seeding: each category is checked independently so
/// new seed data (e.g. dummy block/module presets) gets added even if
/// the DB was created before those features existed.
///
/// Returns `true` if any seeding was performed, `false` if fully up-to-date.
pub async fn seed_if_empty(db: &DatabaseConnection) -> StorageResult<bool> {
    let existing_module_presets = crate::module_repo::list_module_presets(db, None).await?;
    let existing_block_presets = crate::block_repo::list_block_presets(db, None).await?;
    let mut seeded = false;

    // Full seed: no module presets means fresh DB
    if existing_module_presets.is_empty() {
        let defaults = build_guitar_rig();
        seed_guitar_defaults(db, &defaults).await?;
        seeded = true;
    } else {
        tracing::debug!(
            "Core data already seeded ({} module presets)",
            existing_module_presets.len()
        );

        // Incremental: seed dummy block presets if missing
        if existing_block_presets.is_empty() {
            let dummy_blocks = dummy::all_dummy_blocks();
            seed_dummy_block_presets(db, &dummy_blocks).await?;
            tracing::info!(
                "Incremental seed: added {} dummy block presets",
                dummy_blocks.len()
            );
            seeded = true;
        }

        // Incremental: seed dummy module presets if missing.
        // Check for any module preset whose name starts with "Dummy " as marker.
        let has_dummy_modules = existing_module_presets
            .iter()
            .any(|p| p.name.starts_with("Dummy "));
        if !has_dummy_modules {
            let dummy_modules = module_dummy::all_dummy_module_presets();
            seed_dummy_module_presets(db, &dummy_modules).await?;
            tracing::info!(
                "Incremental seed: added {} dummy module presets",
                dummy_modules.len()
            );
            seeded = true;
        }
    }

    if !seeded {
        tracing::debug!("Database fully seeded, nothing to do");
    }
    Ok(seeded)
}

async fn seed_guitar_defaults(
    db: &DatabaseConnection,
    defaults: &GuitarRigDefaults,
) -> StorageResult<()> {
    seed_module_presets(db, &defaults.rig.module_presets).await?;
    seed_presets(db, &defaults.presets).await?;
    seed_profiles(db, &defaults.profiles).await?;
    seed_songs(db, &defaults.songs).await?;

    // Seed dummy block presets for every block type (for testing overrides)
    let dummy_blocks = dummy::all_dummy_blocks();
    seed_dummy_block_presets(db, &dummy_blocks).await?;

    // Seed dummy module presets for every module type
    let dummy_modules = module_dummy::all_dummy_module_presets();
    seed_dummy_module_presets(db, &dummy_modules).await?;

    tracing::info!(
        "Seeded DB: {} module presets, {} presets, {} profiles, {} songs, {} dummy block presets, {} dummy module presets",
        defaults.rig.module_presets.len(),
        defaults.presets.len(),
        defaults.profiles.len(),
        defaults.songs.len(),
        dummy_blocks.len(),
        dummy_modules.len(),
    );
    Ok(())
}

// ── Module Presets + Snapshots ────────────────────────────────────────────

async fn seed_module_presets(
    db: &DatabaseConnection,
    module_presets: &[ModulePreset],
) -> StorageResult<()> {
    for mp in module_presets {
        let now = Utc::now().fixed_offset();
        let blocks_json = facet_bridge::to_json_value(&mp.blocks)?;
        let macros_json = facet_bridge::to_json_value(&mp.macros)?;
        let tags_json = facet_bridge::to_json_value(&mp.tags)?;

        module_preset_entity::ActiveModel {
            id: Set(mp.id.into()),
            name: Set(mp.name.clone()),
            module_type: Set(mp.module_type.display_name().to_string()),
            description: Set(mp.description.clone()),
            blocks: Set(blocks_json),
            macros: Set(macros_json),
            tags: Set(tags_json),
            is_template: Set(true),
            is_deleted: Set(false),
            created_at: Set(now),
            updated_at: Set(now),
        }
        .insert(db)
        .await?;

        seed_module_snapshots(db, mp.id.into(), &mp.snapshots, mp.default_snapshot_id).await?;
    }
    Ok(())
}

async fn seed_module_snapshots(
    db: &DatabaseConnection,
    module_preset_id: uuid::Uuid,
    snapshots: &[DomainModuleSnapshot],
    default_snapshot_id: Option<signal_proto::id::ModuleSnapshotId>,
) -> StorageResult<()> {
    for snap in snapshots {
        let now = Utc::now().fixed_offset();
        let overrides_json = facet_bridge::to_json_value(&snap.block_overrides)?;
        let tags_json = facet_bridge::to_json_value(&snap.tags)?;
        let is_default = default_snapshot_id == Some(snap.id);

        module_snapshot::ActiveModel {
            id: Set(snap.id.into()),
            module_preset_id: Set(module_preset_id),
            name: Set(snap.name.clone()),
            block_overrides: Set(overrides_json),
            is_default: Set(is_default),
            tags: Set(tags_json),
            created_at: Set(now),
            updated_at: Set(now),
        }
        .insert(db)
        .await?;
    }
    Ok(())
}

// ── Top-level Presets + Snapshots ────────────────────────────────────────

async fn seed_presets(db: &DatabaseConnection, presets: &[Preset]) -> StorageResult<()> {
    for p in presets {
        let now = Utc::now().fixed_offset();
        let data_json = facet_bridge::to_json_value(p)?;
        let category_json = facet_bridge::to_json_value(&p.category)?;
        let tags_json = facet_bridge::to_json_value(&p.tags)?;

        preset_entity::ActiveModel {
            id: Set(p.id.into()),
            name: Set(p.name.clone()),
            description: Set(p.description.clone()),
            author_id: Set(None),
            category: Set(category_json),
            tags: Set(tags_json),
            data: Set(data_json),
            is_public: Set(false),
            is_deleted: Set(false),
            is_favorite: Set(false),
            is_template: Set(true),
            version: Set(1),
            created_at: Set(now),
            updated_at: Set(now),
        }
        .insert(db)
        .await?;

        seed_preset_snapshots(db, p.id.into(), &p.snapshots).await?;
    }
    Ok(())
}

async fn seed_preset_snapshots(
    db: &DatabaseConnection,
    preset_id: uuid::Uuid,
    snapshots: &[Snapshot],
) -> StorageResult<()> {
    for snap in snapshots {
        let now = Utc::now().fixed_offset();
        let snap_json = facet_bridge::to_json_value(snap)?;

        snapshot_entity::ActiveModel {
            id: Set(snap.id.into()),
            preset_id: Set(preset_id),
            name: Set(snap.name.clone()),
            data: Set(snap_json),
            created_at: Set(now),
            updated_at: Set(now),
        }
        .insert(db)
        .await?;
    }
    Ok(())
}

// ── Profiles + Scene Templates ───────────────────────────────────────────

async fn seed_profiles(db: &DatabaseConnection, profiles: &[Profile]) -> StorageResult<()> {
    for p in profiles {
        let now = Utc::now().fixed_offset();
        let tags_json = facet_bridge::to_json_value(&p.tags)?;
        let metadata_json = facet_bridge::to_json_value(&p.metadata)?;

        let default_scene_id = p.default_scene_template_id.map(|id| id.into());

        profile_entity::ActiveModel {
            id: Set(p.id.into()),
            name: Set(p.name.clone()),
            rig_id: Set(p.rig_id.into()),
            description: Set(p.description.clone()),
            tags: Set(tags_json),
            metadata: Set(metadata_json),
            default_scene_template_id: Set(default_scene_id),
            is_template: Set(true),
            is_deleted: Set(false),
            created_at: Set(now),
            updated_at: Set(now),
        }
        .insert(db)
        .await?;

        seed_scene_templates(db, p.id.into(), &p.scene_templates).await?;
    }
    Ok(())
}

async fn seed_scene_templates(
    db: &DatabaseConnection,
    profile_id: uuid::Uuid,
    templates: &[SceneTemplate],
) -> StorageResult<()> {
    for (i, t) in templates.iter().enumerate() {
        let now = Utc::now().fixed_offset();
        let module_overrides_json = facet_bridge::to_json_value(&t.module_overrides)?;
        let block_overrides_json = facet_bridge::to_json_value(&t.block_overrides)?;
        let parameter_state_json = facet_bridge::to_json_value(&t.parameter_state)?;
        let tags_json = facet_bridge::to_json_value(&t.tags)?;

        // Extract preset_id from PresetReference
        let preset_id = match &t.preset_reference {
            PresetReference::Direct { preset_id } => (*preset_id).into(),
            PresetReference::Category { .. } => {
                // Category references can't be stored as a direct UUID —
                // skip or use a nil UUID. Seed data should always use Direct.
                tracing::warn!(
                    "Scene template '{}' uses category reference, skipping",
                    t.name
                );
                continue;
            }
        };

        let snapshot_id: Option<uuid::Uuid> = t.default_snapshot_id.map(|id| id.into());

        scene_template::ActiveModel {
            id: Set(t.id.into()),
            profile_id: Set(profile_id),
            name: Set(t.name.clone()),
            preset_id: Set(preset_id),
            snapshot_id: Set(snapshot_id),
            module_overrides: Set(module_overrides_json),
            block_overrides: Set(block_overrides_json),
            parameter_state: Set(parameter_state_json),
            sort_order: Set(i as i32),
            tags: Set(tags_json),
            created_at: Set(now),
            updated_at: Set(now),
        }
        .insert(db)
        .await?;
    }
    Ok(())
}

// ── Songs + Scenes ───────────────────────────────────────────────────────

async fn seed_songs(db: &DatabaseConnection, songs: &[PerformanceSong]) -> StorageResult<()> {
    for s in songs {
        let now = Utc::now().fixed_offset();
        let module_overrides_json = facet_bridge::to_json_value(&s.module_overrides)?;
        let tags_json = facet_bridge::to_json_value(&s.tags)?;
        let linked_song_id: Option<uuid::Uuid> = s.linked_song_id.map(|id| id.into());

        performance_song::ActiveModel {
            id: Set(s.id.into()),
            name: Set(s.name.clone()),
            artist: Set(s.artist.clone()),
            auto_advance: Set(s.auto_advance),
            linked_song_id: Set(linked_song_id),
            module_overrides: Set(module_overrides_json),
            tags: Set(tags_json),
            is_template: Set(true),
            is_deleted: Set(false),
            created_at: Set(now),
            updated_at: Set(now),
        }
        .insert(db)
        .await?;

        seed_song_scenes(db, s.id.into(), &s.scenes).await?;
    }
    Ok(())
}

async fn seed_song_scenes(
    db: &DatabaseConnection,
    song_id: uuid::Uuid,
    scenes: &[Scene],
) -> StorageResult<()> {
    for (i, scene) in scenes.iter().enumerate() {
        let now = Utc::now().fixed_offset();
        let transition_json = facet_bridge::to_json_value(&scene.transition)?;
        let midi_triggers_json = facet_bridge::to_json_value(&scene.midi_triggers)?;
        let module_overrides_json = facet_bridge::to_json_value(&scene.module_overrides)?;
        let block_overrides_json = facet_bridge::to_json_value(&scene.block_overrides)?;
        let tags_json = facet_bridge::to_json_value(&scene.tags)?;
        let snapshot_id: Option<uuid::Uuid> = scene.snapshot_id.map(|id| id.into());

        song_scene::ActiveModel {
            id: Set(scene.id.into()),
            song_id: Set(song_id),
            name: Set(scene.name.clone()),
            preset_id: Set(scene.preset_id.into()),
            snapshot_id: Set(snapshot_id),
            transition: Set(transition_json),
            midi_triggers: Set(midi_triggers_json),
            module_overrides: Set(module_overrides_json),
            block_overrides: Set(block_overrides_json),
            sort_order: Set(i as i32),
            tags: Set(tags_json),
            created_at: Set(now),
            updated_at: Set(now),
        }
        .insert(db)
        .await?;
    }
    Ok(())
}

// ── Dummy Block Presets + Snapshots ──────────────────────────────────────

async fn seed_dummy_block_presets(db: &DatabaseConnection, blocks: &[Block]) -> StorageResult<()> {
    for block in blocks {
        let plugin_id_json = facet_bridge::to_json_value(&block.plugin_id)?;
        let tags_json = serde_json::json!([]);
        let block_type_str = block.block_type.display_name();

        let preset_id = crate::block_repo::create_block_preset(
            db,
            &block.name,
            block_type_str,
            Some(plugin_id_json),
            None,
            block.description.as_deref(),
            tags_json,
        )
        .await?;

        // Create 4 snapshots per dummy block preset
        for (i, name) in dummy::DUMMY_SNAPSHOT_NAMES.iter().enumerate() {
            let is_default = i == 0;
            let params = serde_json::json!({});
            crate::block_repo::create_block_snapshot(db, preset_id, name, params, None, is_default)
                .await?;
        }
    }
    Ok(())
}

// ── Dummy Module Presets + Snapshots ────────────────────────────────────

async fn seed_dummy_module_presets(
    db: &DatabaseConnection,
    modules: &[module_dummy::DummyModulePreset],
) -> StorageResult<()> {
    for module in modules {
        let module_type_str = module.module_type.display_name();
        let tags_json = serde_json::json!([]);

        let preset_id = crate::module_repo::create_module_preset(
            db,
            &module.name,
            module_type_str,
            Some(&module.description),
            serde_json::json!([]), // empty blocks
            serde_json::json!([]), // empty macros
            tags_json,
        )
        .await?;

        // Create 4 snapshots per dummy module preset
        for (i, name) in module_dummy::DUMMY_SNAPSHOT_NAMES.iter().enumerate() {
            let is_default = i == 0;
            let overrides = serde_json::json!([]);
            let snap_tags = serde_json::json!([]);
            crate::module_repo::create_module_snapshot(
                db, preset_id, name, overrides, is_default, snap_tags,
            )
            .await?;
        }
    }
    Ok(())
}

// ── Tests ────────────────────────────────────────────────────────────────

#[cfg(test)]
mod tests {
    use super::*;
    use sea_orm::Database;
    use sea_orm_migration::MigratorTrait;

    async fn test_db() -> DatabaseConnection {
        let db = Database::connect("sqlite::memory:").await.unwrap();
        crate::Migrator::up(&db, None).await.unwrap();
        db
    }

    #[tokio::test]
    async fn seed_guitar_defaults_inserts_all_data() {
        let db = test_db().await;

        let seeded = seed_if_empty(&db).await.unwrap();
        assert!(seeded, "should seed on empty DB");

        // Verify module presets
        let module_presets = crate::module_repo::list_module_presets(&db, None)
            .await
            .unwrap();
        assert!(
            module_presets.len() >= 10,
            "expected at least 10 module presets, got {}",
            module_presets.len()
        );

        // Verify module snapshots exist for the first module preset
        let first_mp = &module_presets[0];
        let snapshots = crate::module_repo::list_module_snapshots(&db, first_mp.id)
            .await
            .unwrap();
        assert!(
            !snapshots.is_empty(),
            "first module preset should have snapshots"
        );

        // Verify top-level presets
        let presets = crate::preset_repo::list_presets(&db, true).await.unwrap();
        assert_eq!(presets.len(), 10, "expected 10 presets");

        // Verify preset snapshots
        let first_preset = &presets[0];
        let preset_snaps = crate::preset_repo::list_preset_snapshots(&db, first_preset.id)
            .await
            .unwrap();
        assert!(
            !preset_snaps.is_empty(),
            "first preset should have snapshots"
        );

        // Verify profiles
        let profiles = crate::profile_repo::list_profiles(&db).await.unwrap();
        assert_eq!(profiles.len(), 3, "expected 3 profiles");

        // Verify scene templates
        let first_profile = &profiles[0];
        let scenes = crate::profile_repo::list_scene_templates(&db, first_profile.id)
            .await
            .unwrap();
        assert!(
            !scenes.is_empty(),
            "first profile should have scene templates"
        );

        // Verify songs
        let songs = crate::song_repo::list_songs(&db).await.unwrap();
        assert_eq!(songs.len(), 5, "expected 5 songs");

        // Verify song scenes
        let first_song = &songs[0];
        let song_scenes = crate::song_repo::list_song_scenes(&db, first_song.id)
            .await
            .unwrap();
        assert!(!song_scenes.is_empty(), "first song should have scenes");

        // Verify dummy block presets
        let block_presets = crate::block_repo::list_block_presets(&db, None)
            .await
            .unwrap();
        assert_eq!(
            block_presets.len(),
            33,
            "expected 33 dummy block presets (one per BlockType)"
        );

        // Verify each block preset has 4 snapshots
        for bp in &block_presets {
            let snaps = crate::block_repo::list_block_snapshots(&db, bp.id)
                .await
                .unwrap();
            assert_eq!(
                snaps.len(),
                4,
                "block preset '{}' should have 4 snapshots, got {}",
                bp.name,
                snaps.len()
            );
            // First snapshot should be the default
            assert!(snaps[0].is_default, "first snapshot should be default");
        }

        // Verify dummy module presets (19 module types × 1 dummy each)
        let dummy_module_presets: Vec<_> = module_presets
            .iter()
            .filter(|p| p.name.starts_with("Dummy "))
            .collect();
        assert_eq!(
            dummy_module_presets.len(),
            19,
            "expected 19 dummy module presets (one per ModuleType), got {}",
            dummy_module_presets.len()
        );

        // Verify each dummy module preset has 4 snapshots
        for dmp in &dummy_module_presets {
            let snaps = crate::module_repo::list_module_snapshots(&db, dmp.id)
                .await
                .unwrap();
            assert_eq!(
                snaps.len(),
                4,
                "dummy module preset '{}' should have 4 snapshots, got {}",
                dmp.name,
                snaps.len()
            );
            assert!(
                snaps[0].is_default,
                "first module snapshot should be default"
            );
        }
    }

    #[tokio::test]
    async fn seed_is_idempotent() {
        let db = test_db().await;

        let first = seed_if_empty(&db).await.unwrap();
        assert!(first, "first seed should insert data");

        let second = seed_if_empty(&db).await.unwrap();
        assert!(!second, "second seed should be a no-op");

        // Counts should be unchanged
        let presets = crate::preset_repo::list_presets(&db, true).await.unwrap();
        assert_eq!(presets.len(), 10);
    }
}
