//! /guides — the guides wiki vault.
//!
//! The guides are a portable markdown vault at `docs/guides/**/*.md`
//! (frontmatter: `title`, `kind`, optional `mode` / `category`),
//! rendered by the in-tree `editor::Editor` in its read-only mode with
//! Obsidian-style live preview, and navigated through `[[wikilinks]]`,
//! a note explorer, and the Task knowledge graph
//! (`view_knowledge_graph`).
//!
//! Loading:
//! - release / native: the vault is embedded at build time
//!   (`embedded::VAULT`, generated by build.rs);
//! - dev on wasm (`debug_assertions`): the same files are fetched over
//!   HTTP from the dx dev server (bundled as the `assets/guides`
//!   folder asset, a symlink to `docs/guides`), so editing a note
//!   updates the site without a rebuild. The embedded copy is the file
//!   LIST either way — adding a note needs a rebuild, editing doesn't.

use std::collections::BTreeMap;
use std::rc::Rc;

use dioxus::prelude::*;
use editor::editor_view::DecorationSource;
use editor::{Editor, EditorState, markdown};
use architect_ui::lucide_dioxus::{FileText, Folder, Keyboard, Lightbulb, Wrench};
use architect_ui::prelude::*;
use view_knowledge_graph::{KnowledgeGraphView, WikiFile, build_wiki_graph};

use crate::Route;
use crate::components::colors::category_color;
use crate::components::input_tutorial::embedded::{MEDIA_ASSETS, VAULT};
use crate::components::modes::find_mode;

// ---------------------------------------------------------------------------
// Vault model + loading
// ---------------------------------------------------------------------------

/// One vault note: path is vault-relative (`reaper/transport.md`).
#[derive(Clone, PartialEq)]
pub struct VaultNote {
    pub path: String,
    pub content: String,
}

impl VaultNote {
    /// File stem — the wikilink / graph-node id (`transport`).
    pub fn stem(&self) -> &str {
        let file = self.path.rsplit('/').next().unwrap_or(&self.path);
        file.strip_suffix(".md").unwrap_or(file)
    }

    /// Display title: frontmatter `title:`, else de-dashed stem.
    pub fn title(&self) -> String {
        fm_field(&self.content, "title")
            .unwrap_or_else(|| self.stem().replace('-', " "))
    }
}

/// Read a scalar `key: value` line from the note's YAML frontmatter.
pub fn fm_field(content: &str, key: &str) -> Option<String> {
    let fm = view_knowledge_graph::parse::frontmatter(content);
    for line in fm.lines() {
        if let Some(rest) = line.trim_end().strip_prefix(key) {
            if let Some(val) = rest.strip_prefix(':') {
                let val = val
                    .trim()
                    .trim_start_matches(['"', '\''])
                    .trim_end_matches(['"', '\'']);
                if !val.is_empty() {
                    return Some(val.to_string());
                }
            }
        }
    }
    None
}

/// The whole embedded vault (also the dev-mode file list).
pub fn embedded_vault() -> Vec<VaultNote> {
    VAULT
        .iter()
        .map(|n| VaultNote {
            path: n.id.to_string(),
            content: n.styx.to_string(),
        })
        .collect()
}

/// Load the vault. Release/native: the embedded copy. Dev on wasm:
/// fetch each note from the dx dev server through its per-file
/// `asset!` URL (see build.rs `VAULT_ASSETS`) — dx hot-reloads
/// single-file assets in place (same served URL, no rebuild), so note
/// edits show up on the next load (per-file fallback to the embedded
/// copy).
pub async fn load_vault() -> Vec<VaultNote> {
    #[cfg(all(target_arch = "wasm32", debug_assertions))]
    {
        use crate::components::input_tutorial::embedded::VAULT_ASSETS;
        let mut notes = embedded_vault();
        for note in &mut notes {
            let Some((_, asset)) = VAULT_ASSETS.iter().find(|(p, _)| *p == note.path) else {
                continue;
            };
            let url = format!("{asset}?t={}", js_sys::Date::now() as u64);
            if let Some(text) = fetch_text(&url).await {
                note.content = text;
            }
        }
        notes
    }
    #[cfg(not(all(target_arch = "wasm32", debug_assertions)))]
    {
        embedded_vault()
    }
}

#[cfg(all(target_arch = "wasm32", debug_assertions))]
async fn fetch_text(url: &str) -> Option<String> {
    use wasm_bindgen::JsCast;
    use wasm_bindgen_futures::JsFuture;
    let win = web_sys::window()?;
    let resp = JsFuture::from(win.fetch_with_str(url)).await.ok()?;
    let resp: web_sys::Response = resp.dyn_into().ok()?;
    if !resp.ok() {
        return None;
    }
    // The dx dev server SPA-fallbacks unknown paths to index.html —
    // treat an HTML payload as a miss so we keep the embedded copy.
    let text = JsFuture::from(resp.text().ok()?).await.ok()?;
    let text = text.as_string()?;
    (!text.trim_start().starts_with("<!DOCTYPE")).then_some(text)
}

// ---------------------------------------------------------------------------
// Wikilink resolution (mirror of view_knowledge_graph::parse::resolve_target)
// ---------------------------------------------------------------------------

/// Resolve a wikilink target (`Transport`, `Input System`,
/// `transport#Rolling`, `reaper|REAPER Guide`) to a note. Matches the
/// file stem case-insensitively with whitespace→dash normalization,
/// falling back to the frontmatter title.
pub fn resolve_note<'a>(notes: &'a [VaultNote], target: &str) -> Option<&'a VaultNote> {
    let page = target.split(['#', '|']).next().unwrap_or(target).trim();
    if page.is_empty() {
        return None;
    }
    let norm = page.to_ascii_lowercase().replace(char::is_whitespace, "-");
    notes
        .iter()
        .find(|n| n.stem().to_ascii_lowercase() == norm)
        .or_else(|| {
            notes.iter().find(|n| {
                n.title()
                    .to_ascii_lowercase()
                    .replace(char::is_whitespace, "-")
                    == norm
            })
        })
}

/// Resolve URL segments (`["reaper", "transport"]`) to a note path:
/// `<joined>.md`, then the Obsidian folder-note `<joined>/<last>.md`;
/// empty segments land on the vault index `guides.md`.
pub fn resolve_route<'a>(notes: &'a [VaultNote], segs: &[String]) -> Option<&'a VaultNote> {
    let joined = segs.join("/");
    if joined.is_empty() {
        return notes.iter().find(|n| n.path == "guides.md");
    }
    let flat = format!("{joined}.md");
    let folder = format!("{joined}/{}.md", segs.last().map(String::as_str).unwrap_or(""));
    notes
        .iter()
        .find(|n| n.path.eq_ignore_ascii_case(&flat))
        .or_else(|| notes.iter().find(|n| n.path.eq_ignore_ascii_case(&folder)))
}

/// Route for a note path — folder notes (`reaper/reaper.md`) collapse
/// to their folder URL (`/guides/reaper`), the vault index to /guides.
pub fn note_route(path: &str) -> Route {
    let no_ext = path.strip_suffix(".md").unwrap_or(path);
    let mut segs: Vec<String> = no_ext.split('/').map(str::to_string).collect();
    if segs.len() >= 2 && segs[segs.len() - 1] == segs[segs.len() - 2] {
        segs.pop();
    }
    if segs.as_slice() == ["guides"] {
        return Route::GuidesPage {};
    }
    Route::GuideNotePage { path: segs }
}

// ---------------------------------------------------------------------------
// VaultLookup for the editor's live-preview pass
// ---------------------------------------------------------------------------

/// Wikilink/embed resolution for the editor decorations: resolved
/// links render purple instead of red, `![[embeds]]` get previews.
struct SiteVaultIndex {
    notes: Vec<VaultNote>,
}

impl SiteVaultIndex {
    fn body_preview(content: &str) -> String {
        body_without_frontmatter(content)
            .trim_start()
            .chars()
            .take(280)
            .collect()
    }
}

/// The note body with its yaml frontmatter block stripped — the
/// metadata renders as chips, not as a properties panel.
pub fn body_without_frontmatter(content: &str) -> &str {
    if view_knowledge_graph::parse::frontmatter(content).is_empty() {
        return content;
    }
    content
        .strip_prefix("---\n")
        .and_then(|r| r.find("\n---").map(|i| r[i + 4..].trim_start_matches('\n')))
        .unwrap_or(content)
}

// ---------------------------------------------------------------------------
// Guide screencast media (`gif` fences → embedded <img>/<video>)
// ---------------------------------------------------------------------------

/// The served URL for a screencast, by its logical name (the eventual
/// media filename stem, e.g. `transport-play`). Falls back to the
/// generic animated placeholder until a real recording is dropped into
/// `assets/guides-media/` under that stem. See `build.rs` `MEDIA_ASSETS`.
fn media_url(name: &str) -> Option<String> {
    let by = |stem: &str| MEDIA_ASSETS.iter().find(|(s, _)| *s == stem);
    by(name.trim())
        .or_else(|| by("_placeholder"))
        .map(|(_, asset)| asset.to_string())
}

/// Resolved media for a screencast name: `(url, is_video)`. Video
/// extensions render as a `<video>`, everything else as an `<img>`.
fn media_render(name: &str) -> Option<(String, bool)> {
    let url = media_url(name)?;
    let ext = url.rsplit('.').next().map(str::to_ascii_lowercase);
    let is_video = matches!(ext.as_deref(), Some("mp4" | "webm" | "mov" | "ogv"));
    Some((url, is_video))
}

/// One piece of a rendered note: either a run of markdown or a
/// screencast block (16:9 media beside a notes column). The vault view
/// renders each `Md` run in its own read-only editor and each `Cast` as
/// a native side-by-side block. `media_right` puts the media on the
/// right (text left) instead of the default media-left.
#[derive(Clone, PartialEq)]
pub enum Segment {
    Md(String),
    Cast {
        name: String,
        side_md: String,
        media_right: bool,
    },
}

/// Split a note body into markdown runs and screencast blocks. A
/// `` ```gif `` fence becomes a [`Segment::Cast`]:
///
/// The example is fenced with four backticks so the three-backtick
/// fence inside it doesn't close it early.
///
/// ````text
/// ```gif
/// transport-play                 ← media name (future filename stem)
/// Space plays and stops.         ← caption / notes column (markdown:
/// - Cursor returns to the start    bullets, **bold**, [[links]], and
/// - Great for repeated takes       `kbd:@` refs all render)
/// ```
/// ````
///
/// The info string picks the side: `` ```gif `` (or `` ```gif left ``)
/// puts the media on the left, `` ```gif right `` puts it on the right
/// (text left).
/// The first non-empty body line is the media NAME; everything after is
/// the side-column markdown. Keeping the source as a fence — not a raw
/// `![[…]]` — is deliberate: the vault's `[[wikilink]]` resolver and
/// knowledge graph must never see media embeds as note links.
pub fn parse_note_segments(body: &str) -> Vec<Segment> {
    let mut segs: Vec<Segment> = Vec::new();
    let mut md = String::new();
    let flush = |md: &mut String, segs: &mut Vec<Segment>| {
        if !md.trim().is_empty() {
            segs.push(Segment::Md(std::mem::take(md)));
        } else {
            md.clear();
        }
    };
    let mut lines = body.lines().peekable();
    while let Some(line) = lines.next() {
        let t = line.trim_start();
        // A `gif` fence, optionally with a `left` / `right` side flag.
        let (is_gif, media_right) = match t.strip_prefix("```gif") {
            Some(rest) => match rest.trim() {
                "" | "left" => (true, false),
                "right" => (true, true),
                _ => (false, false),
            },
            None => (false, false),
        };
        if !is_gif {
            md.push_str(line);
            md.push('\n');
            continue;
        }
        flush(&mut md, &mut segs);
        // Consume the fence body up to the closing ```.
        let mut inner: Vec<&str> = Vec::new();
        for l in lines.by_ref() {
            if l.trim_start().starts_with("```") {
                break;
            }
            inner.push(l);
        }
        // First non-empty line is the media name; the rest is the side
        // column markdown.
        let name_idx = inner.iter().position(|l| !l.trim().is_empty());
        let Some(i) = name_idx else { continue };
        let name = inner[i].trim().to_string();
        let side_md = inner[i + 1..].join("\n").trim().to_string();
        segs.push(Segment::Cast {
            name,
            side_md,
            media_right,
        });
    }
    flush(&mut md, &mut segs);
    segs
}

/// `kbd:@action` resolver: action id → the keys currently bound to it
/// in the embedded fasttrackstudio profile (bindings + which-key leaf
/// sequences), plus the shared mode/workflow layers.
pub(crate) struct SiteKbdIndex(std::collections::HashMap<String, String>);

impl SiteKbdIndex {
    pub(crate) fn build() -> Self {
        use crate::components::input_tutorial::embedded::PROFILES;

        fn walk_leaves(
            prefix: &str,
            entries: &[input_config_proto::WhichKeyEntryDef],
            map: &mut std::collections::HashMap<String, String>,
        ) {
            for e in entries {
                let seq = format!("{prefix} {}", e.key);
                if let Some(action) = &e.action {
                    map.entry(action.clone()).or_insert_with(|| seq.clone());
                }
                if let Some(children) = &e.children {
                    walk_leaves(&seq, children, map);
                }
            }
        }

        let mut map = std::collections::HashMap::new();
        if let Some(profile) = PROFILES.iter().find(|p| p.id == "fasttrackstudio") {
            for s in profile.sections {
                let config: input_config_proto::SectionConfig = match facet_styx::from_str(s.styx)
                {
                    Ok(c) => c,
                    Err(_) => continue,
                };
                for b in config.bindings() {
                    map.entry(b.action.clone()).or_insert_with(|| b.keys.clone());
                }
                for tree in config.which_key() {
                    walk_leaves(&tree.prefix, &tree.entries, &mut map);
                }
            }
        }
        // Mode/workflow layers, so notes about modal bindings
        // (take-ranking etc.) resolve too.
        for m in crate::components::modes::load_modes() {
            for b in &m.bindings {
                map.entry(b.action.clone()).or_insert_with(|| b.keys.clone());
            }
        }
        Self(map)
    }
}

impl markdown::KbdLookup for SiteKbdIndex {
    fn keys_for_action(&self, action: &str) -> Option<String> {
        self.0.get(action).cloned()
    }
}

impl markdown::VaultLookup for SiteVaultIndex {
    fn lookup_block(&self, _uuid: &str) -> Option<markdown::VaultBlockHit> {
        None
    }

    fn lookup_page(&self, name: &str) -> Option<markdown::VaultPageHit> {
        resolve_note(&self.notes, name).map(|n| markdown::VaultPageHit {
            preview: Self::body_preview(&n.content),
        })
    }

    fn lookup_section(&self, page: &str, heading: &str) -> Option<String> {
        let note = resolve_note(&self.notes, page)?;
        let mut out: Vec<&str> = Vec::new();
        let mut level = 0usize;
        for line in note.content.lines() {
            let hashes = line.bytes().take_while(|b| *b == b'#').count();
            let is_heading = hashes > 0 && line[hashes..].starts_with(' ');
            if level == 0 {
                if is_heading && line[hashes..].trim() == heading {
                    level = hashes;
                    out.push(line);
                }
            } else {
                if is_heading && hashes <= level {
                    break;
                }
                out.push(line);
            }
        }
        (!out.is_empty()).then(|| out.join("\n"))
    }

    fn lookup_block_short(&self, _page: &str, _short_id: &str) -> Option<String> {
        None
    }
}

// ---------------------------------------------------------------------------
// Frontmatter chips
// ---------------------------------------------------------------------------

fn kind_meta(kind: &str) -> (&'static str, Element) {
    match kind {
        "input" => ("#38bdf8", rsx! { Keyboard { class: "w-3.5 h-3.5" } }),
        "setup" => ("#10b981", rsx! { Wrench { class: "w-3.5 h-3.5" } }),
        _ => ("#a78bfa", rsx! { Lightbulb { class: "w-3.5 h-3.5" } }),
    }
}

/// Kind / mode / category chips derived from a note's frontmatter.
#[component]
fn NoteChips(content: String) -> Element {
    let kind = fm_field(&content, "kind");
    let mode = fm_field(&content, "mode");
    let category = fm_field(&content, "category");

    rsx! {
        div { class: "flex flex-wrap items-center gap-2",
            if let Some(k) = kind {
                {
                    let (color, icon) = kind_meta(&k);
                    rsx! {
                        span {
                            class: "inline-flex items-center gap-1.5 text-[0.65rem] px-2 py-0.5 rounded-full font-medium uppercase tracking-wider",
                            style: "color: {color}; background-color: {color}1a; border: 1px solid {color}40;",
                            {icon}
                            "{k}"
                        }
                    }
                }
            }
            if let Some(m) = mode {
                {
                    let color = category_color(&m);
                    let name = find_mode(&m).map(|md| md.name).unwrap_or_else(|| m.clone());
                    rsx! {
                        span {
                            class: "inline-flex items-center gap-1.5 text-[0.65rem] px-2 py-0.5 rounded-full font-medium",
                            style: "color: {color}; background-color: {color}1a; border: 1px solid {color}40;",
                            title: "Activate the {name} mode workflow to use these bindings",
                            span { class: "inline-block w-1.5 h-1.5 rounded-full", style: "background-color: {color};" }
                            "Mode: {name}"
                        }
                    }
                }
            }
            if let Some(c) = category {
                {
                    let color = category_color(&c);
                    let cat = c.clone();
                    rsx! {
                        Link {
                            to: Route::InputPage { category: cat },
                            class: "inline-flex items-center gap-1.5 text-[0.65rem] px-2 py-0.5 rounded-full font-medium hover:brightness-125 transition-all",
                            style: "color: {color}; background-color: {color}1a; border: 1px solid {color}40;",
                            span { class: "inline-block w-1.5 h-1.5 rounded-full", style: "background-color: {color};" }
                            "All {c} shortcuts \u{2192}"
                        }
                    }
                }
            }
        }
    }
}

// ---------------------------------------------------------------------------
// The vault page
// ---------------------------------------------------------------------------

/// Site-theme overrides so the editor blends into the page (the
/// bundled editor.css targets a standalone card layout).
const VAULT_STYLE: &str = "
.guides-vault .editor-root { background: transparent; border: none; padding: 0; min-height: 0; }
.guides-vault .editor-frame { background: transparent; border: none; box-shadow: none; padding: 0; }
/* Reading measure for the read-only doc view — roomier than the
   editable 14px/1.6 default, which stays untouched for Task/editing
   contexts. */
.guides-vault .editor-root { font-size: 16px; line-height: 1.7; }
/* Screencast block: 16:9 media on the left, notes column on the right
   (see ScreencastBlock). The frame is a fixed 16:9 box; the notes
   column reuses the reading editor at a slightly smaller measure. */
.guides-vault .cast-frame {
    display: block;
    width: 100%;
    aspect-ratio: 16 / 9;
    object-fit: cover;
    border: 1px solid rgba(120, 140, 180, 0.22);
    border-radius: 10px;
    box-shadow: 0 8px 30px -12px rgba(0, 0, 0, 0.6);
    background: rgba(20, 24, 33, 0.5);
}
.guides-vault .cast-notes .editor-root { font-size: 0.95rem; line-height: 1.62; }
";

/// `/guides` and `/guides/:..path` — the vault view: note explorer,
/// the note in the read-only editor, and the knowledge graph.
#[component]
pub fn GuidesVault(#[props(default)] path: Vec<String>) -> Element {
    // Load (and in dev re-fetch) the vault whenever the route path
    // changes — that's what makes markdown edits show up on the next
    // navigation or reload without a rebuild.
    let route_key = path.join("/");
    let notes_res = use_resource(use_reactive!(|(route_key,)| async move {
        let _ = route_key;
        load_vault().await
    }));
    let notes: Vec<VaultNote> = notes_res.read().clone().unwrap_or_else(embedded_vault);

    let current = resolve_route(&notes, &path).cloned();

    // The note body, split into markdown runs and screencast blocks
    // (each rendered separately below). The frontmatter is stripped —
    // its metadata renders as chips above the note, not as a properties
    // panel.
    let segments: Vec<Segment> = current
        .as_ref()
        .map(|n| parse_note_segments(body_without_frontmatter(&n.content)))
        .unwrap_or_default();

    // Vault-aware live-preview decorations. The source captures the
    // signal (stable Rc identity across renders); the index inside is
    // swapped whenever the vault loads. The kbd resolver (for
    // `kbd:@action` shortcut refs) is static — built once from the
    // embedded profile + mode layers.
    let mut lookup = use_signal(|| None::<Rc<SiteVaultIndex>>);
    {
        let notes = notes.clone();
        use_effect(use_reactive!(|(notes,)| {
            lookup.set(Some(Rc::new(SiteVaultIndex { notes })));
        }));
    }
    let kbd_index = use_hook(|| Rc::new(SiteKbdIndex::build()));
    let decorations = use_hook(move || {
        DecorationSource::new(move |s: &EditorState| {
            let l = lookup.read();
            let vault_ref = l.as_ref().map(|rc| rc.as_ref() as &dyn markdown::VaultLookup);
            markdown::live_preview_with_lookups(
                s,
                vault_ref,
                Some(kbd_index.as_ref() as &dyn markdown::KbdLookup),
            )
        })
    });

    // Wikilink click → resolve → route. (http links are opened by the
    // editor itself; ignore them here.)
    let notes_for_links = notes.clone();
    let on_link_click = use_callback(move |href: String| {
        if href.contains("://") {
            return;
        }
        if let Some(note) = resolve_note(&notes_for_links, &href) {
            navigator().push(note_route(&note.path));
        }
    });

    // Knowledge graph of the whole vault.
    let graph_files: Vec<WikiFile> = notes
        .iter()
        .map(|n| WikiFile {
            name: n
                .path
                .rsplit('/')
                .next()
                .unwrap_or(&n.path)
                .to_string(),
            path: n.path.clone(),
            content: n.content.clone(),
        })
        .collect();
    let graph = build_wiki_graph(&graph_files);
    let notes_for_graph = notes.clone();
    let on_node_click = move |id: String| {
        if let Some(note) = resolve_note(&notes_for_graph, &id) {
            navigator().push(note_route(&note.path));
        }
    };
    let current_stem = current.as_ref().map(|n| n.stem().to_string());

    let current_path = current.as_ref().map(|n| n.path.clone()).unwrap_or_default();
    let title = current.as_ref().map(VaultNote::title).unwrap_or_default();

    rsx! {
        document::Link { rel: "stylesheet", href: editor::EDITOR_STYLE }
        document::Style { {VAULT_STYLE} }

        // Full-bleed reading canvas (no centered max-w cap): the note
        // sits in a wide flex-1 middle, the explorer hugs the left edge,
        // and the connections graph is pushed out to the far right edge —
        // out of the note's way, in what used to be the container's right
        // margin. The note keeps its comfortable prose measure, now with
        // much more room around it.
        div { class: "guides-vault w-full px-4 lg:px-8 py-10",
            div { class: "flex gap-8 xl:gap-12 items-start",

                // ── Note explorer (left edge) ─────────────────
                nav { class: "hidden lg:block w-56 shrink-0 sticky top-24",
                    div { class: "text-xs uppercase tracking-wider text-muted-foreground mb-2", "Guides vault" }
                    VaultExplorer { notes: notes.clone(), current: current_path.clone() }
                }

                // ── The note (centered in the wide middle) ────
                div { class: "flex-1 min-w-0 flex justify-center",
                    div { class: "w-full max-w-7xl min-w-0",
                        if let Some(note) = current.as_ref() {
                            div { class: "mb-4", NoteChips { content: note.content.clone() } }
                            for (i , seg) in segments.iter().enumerate() {
                                {
                                    match seg {
                                        Segment::Md(text) => rsx! {
                                            MdSegment {
                                                key: "{i}",
                                                content: text.clone(),
                                                decorations: decorations.clone(),
                                                on_link_click,
                                            }
                                        },
                                        Segment::Cast { name, side_md, media_right } => rsx! {
                                            ScreencastBlock {
                                                key: "{i}",
                                                name: name.clone(),
                                                side_md: side_md.clone(),
                                                media_right: *media_right,
                                                decorations: decorations.clone(),
                                                on_link_click,
                                            }
                                        },
                                    }
                                }
                            }
                        } else {
                            div { class: "py-16 text-center",
                                p { class: "text-muted-foreground mb-4", "That note doesn't exist in the guides vault." }
                                Link { to: Route::GuidesPage {}, class: "text-primary hover:underline", "Back to the guides" }
                            }
                        }
                    }
                }

                // ── Connections graph (far right edge) ────────
                aside { class: "hidden xl:block w-72 2xl:w-80 shrink-0 sticky top-24",
                    div { class: "text-xs uppercase tracking-wider text-muted-foreground mb-2", "Connections" }
                    div { class: "rounded-xl border border-border/60 bg-card/40 overflow-hidden h-80",
                        KnowledgeGraphView {
                            graph,
                            active: current_stem.clone(),
                            on_node_click,
                        }
                    }
                    if !title.is_empty() {
                        p { class: "mt-2 text-[0.65rem] text-muted-foreground",
                            "Click a node to open its note \u{00b7} drag to pan \u{00b7} scroll to zoom. Current: {title}."
                        }
                    }
                }
            }
        }
    }
}

/// One markdown run of a note, rendered in its own read-only editor
/// (reseeded when its content changes). Reading mode hides every source
/// marker regardless of caret.
#[component]
fn MdSegment(
    content: String,
    decorations: DecorationSource,
    on_link_click: Callback<String>,
) -> Element {
    let mut state = use_signal(|| EditorState::new(String::new()));
    use_effect(use_reactive!(|(content,)| {
        if state.peek().doc.to_string() != content {
            let mut s = EditorState::new(content.clone());
            s.reading_mode = true;
            state.set(s);
        }
    }));
    rsx! {
        Editor { state, decorations: decorations.clone(), editable: false, on_link_click }
    }
}

/// A screencast block: the 16:9 media beside a notes column that fills
/// the width (caption, bullets, `kbd:@` refs, `[[links]]` — all rendered
/// as markdown). `media_right` flips the pair so the text sits on the
/// left and the media on the right; otherwise media-left. Stacks
/// vertically on narrow screens. The media falls back to the animated
/// placeholder until a real recording exists under its name.
#[component]
fn ScreencastBlock(
    name: String,
    side_md: String,
    #[props(default)] media_right: bool,
    decorations: DecorationSource,
    on_link_click: Callback<String>,
) -> Element {
    let media = media_render(&name);
    // Media and notes are always in the same DOM order; on desktop we
    // reverse the row to put the media on the right when asked.
    let row = if media_right { "lg:flex-row-reverse" } else { "lg:flex-row" };
    rsx! {
        div { class: "cast-block flex flex-col {row} gap-6 items-start my-7",
            // ── 16:9 media (left) ─────────────────────────
            div { class: "cast-media w-full lg:w-[34rem] xl:w-[38rem] shrink-0",
                {
                    match media {
                        Some((url, true)) => rsx! {
                            video { class: "cast-frame", src: "{url}", autoplay: true, muted: true, r#loop: true }
                        },
                        Some((url, false)) => rsx! {
                            img { class: "cast-frame", src: "{url}", alt: "{name}" }
                        },
                        None => rsx! {},
                    }
                }
            }
            // ── notes column (fills the width, right) ─────
            if !side_md.trim().is_empty() {
                div { class: "cast-notes flex-1 min-w-0 lg:pt-1",
                    MdSegment { content: side_md.clone(), decorations: decorations.clone(), on_link_click }
                }
            }
        }
    }
}

// ---------------------------------------------------------------------------
// Explorer
// ---------------------------------------------------------------------------

/// Folder tree from the vault paths: root notes, then one section per
/// directory (folder note first, then its children by title).
#[component]
fn VaultExplorer(notes: Vec<VaultNote>, current: String) -> Element {
    let mut roots: Vec<&VaultNote> = Vec::new();
    let mut dirs: BTreeMap<String, Vec<&VaultNote>> = BTreeMap::new();
    for n in &notes {
        match n.path.split_once('/') {
            Some((dir, _)) => dirs.entry(dir.to_string()).or_default().push(n),
            None => roots.push(n),
        }
    }
    roots.sort_by_key(|n| n.title().to_lowercase());
    for children in dirs.values_mut() {
        // Folder note first, then by title.
        children.sort_by_key(|n| {
            let is_folder_note = n
                .path
                .strip_suffix(".md")
                .is_some_and(|p| p.split('/').rev().take(2).collect::<Vec<_>>().windows(2).all(|w| w[0] == w[1]) && p.contains('/'));
            (!is_folder_note, n.title().to_lowercase())
        });
    }

    rsx! {
        div { class: "flex flex-col gap-0.5",
            for n in roots {
                ExplorerRow { path: n.path.clone(), title: n.title(), depth: 0, current: current.clone(), folder: false }
            }
            for (dir, children) in dirs.iter() {
                div { key: "{dir}", class: "mt-1",
                    div { class: "flex items-center gap-1.5 px-2 py-1 text-xs uppercase tracking-wider text-muted-foreground/70",
                        Folder { class: "w-3.5 h-3.5" }
                        "{dir}"
                    }
                    for n in children.iter() {
                        ExplorerRow { path: n.path.clone(), title: n.title(), depth: 1, current: current.clone(), folder: false }
                    }
                }
            }
        }
    }
}

#[component]
fn ExplorerRow(path: String, title: String, depth: usize, current: String, folder: bool) -> Element {
    let active = path == current;
    let indent = depth * 12 + 8;
    rsx! {
        Link {
            to: note_route(&path),
            class: if active {
                "flex items-center gap-1.5 rounded px-2 py-1 text-sm bg-accent/60 text-foreground"
            } else {
                "flex items-center gap-1.5 rounded px-2 py-1 text-sm text-muted-foreground hover:text-foreground hover:bg-accent/30 transition-colors"
            },
            style: "padding-left: {indent}px;",
            FileText { class: "w-3.5 h-3.5 shrink-0 opacity-60" }
            span { class: "min-w-0 truncate", "{title}" }
        }
    }
}

// ---------------------------------------------------------------------------
// Tests — the vault can't silently drift from the input configs.
// ---------------------------------------------------------------------------

#[cfg(test)]
mod tests {
    use std::collections::HashSet;

    use input_config_proto::{SectionConfig, WhichKeyEntryDef};

    use super::*;
    use crate::components::input_tutorial::embedded::PROFILES;

    #[test]
    fn vault_embeds_and_parses() {
        let notes = embedded_vault();
        assert!(notes.len() >= 6, "guides vault lost notes");
        for n in &notes {
            assert!(!n.title().is_empty(), "{} has no title", n.path);
        }
        // The landing + reaper folder notes exist for the routes.
        assert!(resolve_route(&notes, &[]).is_some(), "vault index note missing");
        assert!(
            resolve_route(&notes, &["reaper".into()]).is_some(),
            "reaper folder note missing"
        );
        assert!(
            resolve_route(&notes, &["reaper".into(), "transport".into()]).is_some(),
            "URL compat: /guides/reaper/transport must resolve"
        );
    }

    /// The ported Keyflow guide: folder note + 10 chapters, sane
    /// frontmatter conversion (title, kind: concept, numeric order
    /// from the docs-site weights), and its ```kf fences intact.
    #[test]
    fn keyflow_guide_ported() {
        let notes = embedded_vault();
        let keyflow: Vec<&VaultNote> = notes
            .iter()
            .filter(|n| n.path.starts_with("keyflow/"))
            .collect();
        assert_eq!(keyflow.len(), 11, "keyflow guide should be 11 notes");

        assert!(
            resolve_route(&notes, &["keyflow".into()]).is_some(),
            "keyflow folder note missing"
        );
        assert!(
            resolve_route(&notes, &["keyflow".into(), "chords".into()]).is_some(),
            "/guides/keyflow/chords must resolve"
        );

        let mut orders = Vec::new();
        for n in &keyflow {
            assert_eq!(
                fm_field(&n.content, "kind").as_deref(),
                Some("concept"),
                "{}: keyflow notes are concept notes",
                n.path
            );
            let order: u32 = fm_field(&n.content, "order")
                .unwrap_or_else(|| panic!("{}: missing order", n.path))
                .parse()
                .unwrap_or_else(|_| panic!("{}: non-numeric order", n.path));
            orders.push(order);
        }
        orders.sort_unstable();
        assert_eq!(
            orders,
            (0..=10).collect::<Vec<u32>>(),
            "chapter order should be the contiguous docs-site weights"
        );

        // The engraved-chart fences survived the conversion.
        let chords = keyflow
            .iter()
            .find(|n| n.path == "keyflow/chords.md")
            .expect("chords chapter");
        assert!(
            chords.content.contains("```kf+\nCmaj7 | F#m7b5 | Bbmaj9 | G7b9\n```"),
            "chords chapter lost its kf+ fence (source + chart together)"
        );
    }

    #[test]
    fn every_wikilink_resolves() {
        let notes = embedded_vault();
        for n in &notes {
            for target in view_knowledge_graph::parse::extract_wikilinks(&n.content) {
                assert!(
                    resolve_note(&notes, &target).is_some(),
                    "{}: wikilink [[{target}]] resolves to no note",
                    n.path
                );
            }
        }
    }

    #[test]
    fn note_routes_round_trip() {
        let notes = embedded_vault();
        for n in &notes {
            let segs = match note_route(&n.path) {
                Route::GuidesPage {} => Vec::new(),
                Route::GuideNotePage { path } => path,
                r => panic!("unexpected route {r:?} for {}", n.path),
            };
            let resolved = resolve_route(&notes, &segs)
                .unwrap_or_else(|| panic!("route for {} resolves to nothing", n.path));
            assert_eq!(resolved.path, n.path, "route round-trip mismatch");
        }
    }

    /// Inline code spans of a markdown body (fenced blocks skipped).
    fn code_spans(md: &str) -> Vec<String> {
        let mut out = Vec::new();
        let mut in_fence = false;
        for line in md.lines() {
            if line.trim_start().starts_with("```") {
                in_fence = !in_fence;
                continue;
            }
            if in_fence {
                continue;
            }
            let mut rest = line;
            while let Some(start) = rest.find('`') {
                let after = &rest[start + 1..];
                let Some(end) = after.find('`') else { break };
                out.push(after[..end].to_string());
                rest = &after[end + 1..];
            }
        }
        out
    }

    /// Does a code span read as a key sequence (`r`, `<C-s>`, `n d`,
    /// `<S-n> s a`)? Multi-char bare words (action ids, commands)
    /// don't.
    fn looks_like_keys(span: &str) -> bool {
        let mut tokens = span.split_whitespace().peekable();
        if tokens.peek().is_none() {
            return false;
        }
        tokens.all(|t| t.chars().count() == 1 || (t.starts_with('<') && t.ends_with('>')))
    }

    /// Every leaf AND branch sequence of a which-key tree, plus the
    /// prefix itself (guides legitimately reference bare prefixes).
    fn walk(prefix: &str, entries: &[WhichKeyEntryDef], out: &mut HashSet<String>) {
        out.insert(prefix.to_string());
        for e in entries {
            let seq = format!("{prefix} {}", e.key);
            out.insert(seq.clone());
            if let Some(children) = &e.children {
                walk(&seq, children, out);
            }
        }
    }

    /// Drift guard, two halves:
    ///
    /// - every `kbd:@action` ref anywhere in the vault must resolve
    ///   through [`SiteKbdIndex`] (base profile + which-key leaves +
    ///   mode layers) — an unresolved ref means the guide points at
    ///   an action nothing is bound to;
    /// - every key-LITERAL shortcut (`kbd:<C-s>`, `kbd:n d`, or a
    ///   bare key-looking code span) in a `kind: input` note must
    ///   exist in the fasttrackstudio profile (bindings + which-key
    ///   sequences/prefixes) or the note's declared `mode:` layer.
    #[test]
    fn input_note_shortcuts_exist_in_configs() {
        use editor::markdown::KbdLookup as _;

        let profile = PROFILES
            .iter()
            .find(|p| p.id == "fasttrackstudio")
            .expect("fasttrackstudio profile embedded");

        let mut base: HashSet<String> = HashSet::new();
        for s in profile.sections {
            let config: SectionConfig = match facet_styx::from_str(s.styx) {
                Ok(c) => c,
                Err(_) => continue,
            };
            for b in config.bindings() {
                base.insert(b.keys.clone());
            }
            for tree in config.which_key() {
                walk(&tree.prefix, &tree.entries, &mut base);
            }
        }
        assert!(!base.is_empty(), "profile produced no key sequences");

        let kbd_index = SiteKbdIndex::build();

        let mut refs_checked = 0;
        let mut literals_checked = 0;
        let mut mode_checked = 0;
        for note in embedded_vault() {
            let is_input = fm_field(&note.content, "kind").as_deref() == Some("input");
            let mode_keys: HashSet<String> = fm_field(&note.content, "mode")
                .map(|mid| {
                    let m = crate::components::modes::find_mode(&mid).unwrap_or_else(|| {
                        panic!("{}: unknown mode {mid:?} in frontmatter", note.path)
                    });
                    m.bindings.iter().map(|b| b.keys.clone()).collect()
                })
                .unwrap_or_default();

            for span in code_spans(&note.content) {
                // Action refs must resolve in EVERY note.
                if let Some(action) = span.strip_prefix("kbd:@") {
                    refs_checked += 1;
                    assert!(
                        kbd_index.keys_for_action(action.trim()).is_some(),
                        "{}: `kbd:@{action}` resolves to no binding in the \
                         fasttrackstudio profile or any mode layer — update \
                         the note or the config",
                        note.path,
                    );
                    continue;
                }
                // Literals only guard input notes.
                if !is_input {
                    continue;
                }
                let literal = span.strip_prefix("kbd:").unwrap_or(&span).trim().to_string();
                if !looks_like_keys(&literal) {
                    continue;
                }
                literals_checked += 1;
                if mode_keys.contains(&literal) {
                    mode_checked += 1;
                    continue;
                }
                assert!(
                    base.contains(&literal),
                    "{}: shortcut `{literal}` does not exist in the fasttrackstudio \
                     profile{} — update the note or the config",
                    note.path,
                    if mode_keys.is_empty() { "" } else { " or its mode's overlays" },
                );
            }
        }
        assert!(refs_checked > 15, "suspiciously few @refs checked ({refs_checked})");
        assert!(
            literals_checked > 3,
            "suspiciously few literals checked ({literals_checked})"
        );
        assert!(mode_checked > 0, "no mode-layered literal was exercised");
    }
}
