// Shared build-script body for the three Task front-end crates.
//
// Each of `apps/task/{desktop,mobile,web}/build.rs` is a one-liner that
// `include!`s this file, so there is one implementation rather than three
// copies (the thing this whole change is about).
//
// WHY THIS EXISTS
// ---------------
// `assets/tailwind.css` is build OUTPUT. It used to be committed — ~19,500
// lines across the three apps — and regenerated by hand, which meant it was
// reliably stale. The committed sheets were 7,053 (web), 6,236 (desktop)
// and 6,229 (mobile) lines; the same inputs regenerate to 8,619 apiece.
// Every utility class added since the last manual run simply did not exist
// in the shipped bundles, and desktop and mobile were additionally missing
// the session-ui and dock classes only the web sheet declared a source for.
//
// It cannot merely be deleted, though: `asset!("/assets/tailwind.css")` is a
// compile-time macro that hard-errors when the file is missing, so a plain
// `cargo check --workspace` (what CI runs) would fail. Hence: the file is
// gitignored, and this script regenerates it as part of the ordinary build.
//
// `tailwindcss` comes from the repo flake (`fts.nativeBuildInputs`, and it
// is now also in the `.#ci` shell for exactly this reason).

use std::path::{Path, PathBuf};
use std::process::Command;

/// `@source` roots declared by `apps/task/tailwind.css`, relative to the
/// repo root. Touching a `.rs` file in any of these can introduce a new
/// utility class, so cargo must re-run this script when they change.
/// (Keep in sync with the `@source` lines in that file.)
const SOURCE_ROOTS: &[&str] = &[
    "crates/task/ui/src",
    "features/task",
    "libs/fts-ui/fts-ui/src",
    "crates/session/ui/src",
    "libs/dock",
];

fn main() {
    let manifest = PathBuf::from(std::env::var("CARGO_MANIFEST_DIR").unwrap());
    // apps/task/<app>/ -> apps/task/
    let task_dir = manifest.parent().unwrap().to_path_buf();
    // apps/task/ -> repo root
    let repo_root = task_dir.parent().unwrap().parent().unwrap().to_path_buf();

    let input = task_dir.join("tailwind.css");
    let out = manifest.join("assets").join("tailwind.css");

    println!("cargo:rerun-if-changed={}", input.display());
    println!("cargo:rerun-if-changed={}", task_dir.join("fts-theme.css").display());
    println!(
        "cargo:rerun-if-changed={}",
        repo_root.join("libs/fts-ui/fts-ui/assets/fts-theme.css").display()
    );
    for root in SOURCE_ROOTS {
        let p = repo_root.join(root);
        if p.exists() {
            println!("cargo:rerun-if-changed={}", p.display());
        }
    }
    // Escape hatch: set TASK_SKIP_TAILWIND=1 to keep whatever sheet is
    // already on disk (useful when iterating on Rust with no CSS changes).
    println!("cargo:rerun-if-env-changed=TASK_SKIP_TAILWIND");

    if std::env::var("TASK_SKIP_TAILWIND").is_ok_and(|v| v != "0") {
        require_existing(&out, "TASK_SKIP_TAILWIND is set");
        return;
    }

    if let Some(parent) = out.parent() {
        std::fs::create_dir_all(parent).ok();
    }

    // cwd MATTERS. Tailwind v4 resolves `@source` globs relative to the CSS
    // file, but its *automatic* content detection is rooted at the working
    // directory — so the same input emits a different sheet depending on
    // where you run it from. Running in the crate dir (apps/task/web) emits
    // ~1,000 fewer rules than the historical `just desktop-css`, which ran
    // from apps/task/ (just sets cwd to the Justfile's directory).
    //
    // Pin cwd to apps/task/ so every caller — this script, `just css`, the
    // Nix image build, the iOS deploy — produces a byte-identical sheet.
    match Command::new("tailwindcss")
        .current_dir(&task_dir)
        .arg("-i")
        .arg(&input)
        .arg("-o")
        .arg(&out)
        .status()
    {
        Ok(status) if status.success() => {}
        Ok(status) => {
            // Tailwind ran but failed. Never let a half-written sheet
            // through — a truncated stylesheet is a silent visual break.
            panic!(
                "tailwindcss failed ({status}) building {} -> {}",
                input.display(),
                out.display()
            );
        }
        Err(e) => {
            require_existing(
                &out,
                &format!("tailwindcss is not on PATH ({e}); enter the repo dev shell (`nix develop`)"),
            );
            println!(
                "cargo:warning=tailwindcss not found — reusing the existing {}. \
                 It may be stale; run `just css` from apps/task/ in the dev shell.",
                out.display()
            );
        }
    }
}

/// The sheet must exist one way or another: `asset!()` fails to compile
/// without it. If we cannot generate it and there is no previous copy,
/// fail loudly and say how to fix it.
fn require_existing(out: &Path, why: &str) {
    if !out.exists() {
        panic!(
            "{why}, and {} does not exist.\n\
             This file is generated build output (it is gitignored). Build it with:\n  \
             cd apps/task && just css\n\
             or enter the dev shell so `tailwindcss` is on PATH.",
            out.display()
        );
    }
}
