[package]
name = "notifications-ui"
version.workspace = true
edition.workspace = true
authors.workspace = true
license.workspace = true

[dependencies]
dioxus = { workspace = true }
notifications-proto.workspace = true
chrono = { workspace = true, features = ["clock", "std", "wasmbind"] }
uuid = { workspace = true, features = ["v4", "js"] }
fts-ui.workspace = true
web-sys = { workspace = true, features = [
    "Notification",
    "NotificationOptions",
    "NotificationPermission",
] }
wasm-bindgen.workspace = true
wasm-bindgen-futures.workspace = true
