[application]
name = "Task"

[web.app]
title = "Task"

[web.resource]
style = []
script = []

[web.resource.dev]
script = []

[bundle]
identifier = "com.codyswright.task"
publisher  = "Cody Wright"
name       = "Task"

[bundle.ios]
minimum_system_version = "16.0"
