[package]
name = "playground"
version = "0.1.0"
authors = ["Cody Wright <acodywright@gmail.com>"]
edition = "2021"

[dependencies]
dioxus = { workspace = true, features = ["router"] }
signal2.workspace = true
signal2-ui.workspace = true
frame-import = { path = "../../../cells/frame/frame-import" }
frame-proto = { path = "../../../cells/frame/frame-proto" }
frame-ui = { path = "../../../cells/frame/frame-ui", features = ["anyrender"] }
anyrender = { workspace = true }
anyrender_vello = { workspace = true }
vello = { workspace = true }
wgpu_context = { workspace = true }
wgpu = { workspace = true }
pollster = { workspace = true }
kurbo = { workspace = true }
peniko = { workspace = true }
tokio = { workspace = true, features = ["time"] }
serde_json = { workspace = true }
lumen-blocks = { git = "https://github.com/Leaf-Computer/lumen-blocks.git", tag = "v0.2.0" }

[features]
default = ["desktop"]
web = ["dioxus/web"]
desktop = ["dioxus/desktop"]
mobile = ["dioxus/mobile"]
