[package]
name = "editor-state"
description = "Document, transactions, selections, and decorations for the Editor."
version.workspace = true
edition.workspace = true
license.workspace = true
authors.workspace = true
rust-version.workspace = true

[dependencies]
editor-syntax = { workspace = true, features = ["default-langs"] }
ropey = { workspace = true }
serde = { workspace = true, optional = true }
thiserror = { workspace = true }

[features]
default = []
serde = ["dep:serde"]
