// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Musical position in measures.beats.subdivisions format
 *
 * Subdivisions are 0-999, where 1000 would equal a full beat.
 * The beat value changes based on the time signature.
 *
 * Examples:
 * - `MusicalPosition { measure: 0, beat: 0, subdivision: 500 }` = 0.0.500 (eighth note in first beat)
 * - `MusicalPosition { measure: 4, beat: 3, subdivision: 400 }` = 4.3.400 (measure 4, beat 3, 40% through the beat)
 */
export type MusicalPosition = { 
/**
 * Measure number (0-indexed)
 */
measure: number, 
/**
 * Beat within the measure (0-indexed)
 */
beat: number, 
/**
 * Subdivision within the beat (0-999, where 1000 = full beat)
 */
subdivision: number, };
