// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { MusicalPosition } from "./MusicalPosition";
import type { TimePosition } from "./TimePosition";

/**
 * Position that contains both musical and time-based representations
 *
 * This allows transport systems to provide position information in multiple formats,
 * making it easier to integrate with different DAWs that may provide different position types.
 */
export type Position = { 
/**
 * Musical position (measure.beat.subdivision)
 */
musical: MusicalPosition, 
/**
 * Time position (minutes:seconds:milliseconds)
 */
time: TimePosition, };
