// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Position } from "./Position";
import type { SectionType } from "./SectionType";

/**
 * Represents a section within a song
 */
export type Section = { 
/**
 * Unique identifier for this section
 */
id: string | null, 
/**
 * Section type
 */
section_type: SectionType, 
/**
 * Optional section number (e.g., 1, 2, 3 for Verse 1, Verse 2, etc.)
 */
number: number | null, 
/**
 * Split letter for consecutive sections (e.g., 'a', 'b', 'c')
 */
split_letter: string | null, 
/**
 * Start position
 */
start_position: Position, 
/**
 * End position
 */
end_position: Position, 
/**
 * Section name (from region name)
 */
name: string, 
/**
 * Optional metadata
 */
metadata: { [key in string]?: string }, };
