// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Represents different types of song sections with their full names and abbreviations
 */
export type SectionType = "Verse" | "Chorus" | "Bridge" | "Intro" | "Outro" | "Instrumental" | { "Pre": SectionType } | { "Post": SectionType };
