// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { SectionType } from "./SectionType";

/**
 * Summary information about a setlist
 */
export type SetlistSummary = { name: string, song_count: number, total_duration: number, total_render_duration: number, section_types: { [key in SectionType]?: number }, songs_with_count_in: number, songs_with_markers: number, };
