// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { SetlistEntry } from "./SetlistEntry";

/**
 * Setlist order management for live performance
 * This represents the sequence of songs across multiple project tabs
 */
export type SetlistOrder = { 
/**
 * Ordered list of songs/tabs in the setlist
 */
entries: Array<SetlistEntry>, 
/**
 * Current position in setlist (0-based index)
 */
current_position: number, };
