// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Position } from "./Position";

/**
 * Represents a song entry in the setlist order
 * This maps to a specific project tab and contains playback position information
 */
export type SetlistEntry = { 
/**
 * Tab index (0-based) - identifies which project tab this song is in
 */
tab_index: number, 
/**
 * Project file path (if available) - for persistence across sessions
 */
project_path: string | null, 
/**
 * Song name for display purposes
 */
song_name: string | null, 
/**
 * Count-in position (if "Count-In" marker exists)
 */
count_in_position: Position | null, 
/**
 * Start position (if "SONGSTART" marker exists)
 */
start_position: Position | null, 
/**
 * Optional metadata
 */
metadata: { [key in string]?: string }, };
