// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Song } from "./Song";

/**
 * Represents a complete setlist
 */
export type Setlist = { 
/**
 * Unique identifier for this setlist
 */
id: string | null, 
/**
 * Setlist name/title
 */
name: string, 
/**
 * List of songs in the setlist
 */
songs: Array<Song>, 
/**
 * Optional metadata (venue, date, etc.)
 */
metadata: { [key in string]?: string }, };
