// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Position } from "./Position";
import type { Section } from "./Section";

/**
 * Represents a song in the setlist
 */
export type Song = { 
/**
 * Unique identifier for this song
 */
id: string | null, 
/**
 * Song name (from the song region name)
 */
name: string, 
/**
 * Count-In marker position (marker named "Count-In")
 */
count_in_position: Position | null, 
/**
 * SONGSTART marker position (render start, where real song content begins)
 */
start_position: Position | null, 
/**
 * SONGEND marker position (last hit of song, but may have audio after)
 */
song_end_position: Position | null, 
/**
 * =END marker position (hard cut, no more audio)
 */
end_position: Position | null, 
/**
 * Song region boundaries (start and end of the entire song region)
 */
song_region_start: Position | null, song_region_end: Position | null, 
/**
 * List of sections in the song (from regions between SONGSTART and SONGEND)
 */
sections: Array<Section>, 
/**
 * Optional metadata (key, tempo, etc.)
 */
metadata: { [key in string]?: string }, };
