// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { SectionType } from "./SectionType";

/**
 * Summary information about a song
 */
export type SongSummary = { name: string, duration: number, render_duration: number, section_count: number, section_types: { [key in SectionType]?: number }, has_count_in: boolean, has_markers: boolean, };
