// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Information about a setlist source
 */
export type SourceInfo = { name: string, is_available: boolean, source_type: string, metadata: { [key in string]?: string }, };
