[package]
name = "reaper_extension"
version.workspace = true
edition.workspace = true
authors.workspace = true
license.workspace = true

[dependencies]
reaper-medium = { git = "https://github.com/helgoboss/reaper-rs.git", branch = "master" }
reaper-low = { git = "https://github.com/helgoboss/reaper-rs.git", branch = "master" }
reaper-macros = { git = "https://github.com/helgoboss/reaper-rs.git", branch = "master" }
reaper-high = { git = "https://github.com/helgoboss/reaper-rs.git", branch = "master" }
tracing = "0.1"
tracing-subscriber = { version = "0.3", features = ["env-filter", "fmt"] }
daw = { path = "../../modules/daw" }
daw-proto = { path = "../../extensions/daw/daw-proto" }
daw-reaper = { path = "../../extensions/daw/daw-reaper" }
extension-runtime = { path = "../../modules/extension-runtime" }
roam = { workspace = true }
tokio = { version = "1.0", features = ["full"] }
anyhow = "1.0"

[lib]
name = "reaper_extension"
crate-type = ["cdylib", "rlib"]

[lints.rust]
unsafe_code = "allow"
unused = { level = "allow", priority = -1 }
