// This file has been generated by Specta. DO NOT EDIT.

import { createTauRPCProxy as createProxy, type InferCommandOutput } from 'taurpc'
type TAURI_CHANNEL<T> = (response: T) => void


export type ApiError = { code: number; message: string }

export type AppStatus = { user_count: number; is_processing: boolean; last_message: string; counter_value: number }

export type ProcessingResult = { success: boolean; message: string; duration_ms: number }

export type TaskProgress = { task_id: string; progress: number; message: string }

export type User = { id: number; name: string; email: string; active: boolean }

const ARGS_MAP = { '':'{"error_occurred":["error"],"get_status":[],"reset_app":[],"status_changed":["status"]}', 'counter':'{"decrement":[],"get_value":[],"increment":[],"reset":[],"set_value":["value"]}', 'tasks':'{"run_long_task":["task_name","duration_seconds","on_progress"],"simulate_batch_processing":["batch_size","on_progress"]}', 'users':'{"create_user":["name","email"],"get_all_users":[],"toggle_user_status":["user_id"]}' }
export type Router = { "": {error_occurred: (error: ApiError) => Promise<void>, 
get_status: () => Promise<AppStatus>, 
reset_app: () => Promise<string>, 
status_changed: (status: AppStatus) => Promise<void>},
"counter": {decrement: () => Promise<number>, 
get_value: () => Promise<number>, 
increment: () => Promise<number>, 
reset: () => Promise<number>, 
set_value: (value: number) => Promise<number>},
"tasks": {run_long_task: (taskName: string, durationSeconds: number, onProgress: TAURI_CHANNEL<TaskProgress>) => Promise<ProcessingResult>, 
simulate_batch_processing: (batchSize: number, onProgress: TAURI_CHANNEL<TaskProgress>) => Promise<ProcessingResult>},
"users": {create_user: (name: string, email: string) => Promise<User>, 
get_all_users: () => Promise<User[]>, 
toggle_user_status: (userId: number) => Promise<User>} };


export const createTauRPCProxy = () => createProxy<Router>(ARGS_MAP)
export type { InferCommandOutput }
