[application]
name = "FastTrackStudio"

[desktop]
title = "FastTrackStudio"

[web.app]

# HTML title tag content
title = "FastTrackStudio"

# include `assets` in web platform
[web.resource]

# Additional CSS style files
style = []

# Additional JavaScript files
script = []

[web.resource.dev]

# Javascript code file
# serve: [dev-server] only
script = []

[bundle]
identifier = "com.fasttrackstudio.desktop"
publisher = "FastTrack Studio"
icon = ["./assets/favicon.ico"]
name = "FastTrackStudio"

[bundle.macos]
minimum_system_version = "13.0"
