// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Position } from "./Position";

/**
 * A marker represents a named point in time on the timeline
 */
export type Marker = { 
/**
 * Unique identifier for this marker (if supported by the source)
 */
id: number | null, 
/**
 * Position in time where this marker is located
 */
position: Position, 
/**
 * Human-readable name for this marker
 */
name: string, 
/**
 * Color for visual representation (RGB value, if supported)
 */
color: number | null, 
/**
 * Implementation-specific flags (e.g., REAPER's marker flags)
 */
flags: number | null, 
/**
 * Whether this marker is locked from editing
 */
locked: boolean | null, 
/**
 * Globally unique identifier (if supported by the source)
 */
guid: string | null, };
