// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { TimeRange } from "./TimeRange";

/**
 * A region represents a named span of time on the timeline
 */
export type Region = { 
/**
 * Unique identifier for this region (if supported by the source)
 */
id: number | null, 
/**
 * Time range that this region spans
 */
time_range: TimeRange, 
/**
 * Human-readable name for this region
 */
name: string, 
/**
 * Color for visual representation (RGB value, if supported)
 */
color: number | null, 
/**
 * Implementation-specific flags (e.g., REAPER's region flags)
 */
flags: number | null, 
/**
 * Whether this region is locked from editing
 */
locked: boolean | null, 
/**
 * Globally unique identifier (if supported by the source)
 */
guid: string | null, };
