// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Position } from "./Position";

/**
 * Time range representing a selection or loop region
 *
 * Contains both start and end positions, each with musical and time representations.
 * This is the base type used for time selections and loop selections in the transport.
 */
export type TimeRange = { 
/**
 * Start position of the range
 */
start: Position, 
/**
 * End position of the range
 */
end: Position, };
