// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Time position in minutes:seconds:milliseconds format
 *
 * This represents an absolute time position, independent of tempo and time signature.
 *
 * Examples:
 * - `TimePosition { minutes: 0, seconds: 5, milliseconds: 250 }` = 0:05.250 (5.25 seconds)
 * - `TimePosition { minutes: 2, seconds: 30, milliseconds: 500 }` = 2:30.500 (2 minutes, 30.5 seconds)
 */
export type TimePosition = { 
/**
 * Minutes component
 */
minutes: number, 
/**
 * Seconds component (0-59)
 */
seconds: number, 
/**
 * Milliseconds component (0-999)
 */
milliseconds: number, };
