[application]
name = "FTS Installer"

[desktop]
title = "FastTrackStudio Installer"

[web.app]
title = "FTS Installer"

[web.resource]
style = []
script = []

[web.resource.dev]
script = []

[bundle]
identifier = "com.fasttrackstudio.installer"
publisher = "FastTrack Studio"
icon = ["./assets/favicon.ico"]
name = "FTS Installer"

[bundle.macos]
minimum_system_version = "13.0"
