--[[
  Dump every mouse-modifier BEHAVIOR name REAPER actually offers.

  Why this exists: reaper-input's behavior tables
  (src/input/mouse_modifiers/behaviors/**, mirrored in action_names.rs)
  were hand-decoded from REAPER's docs and have drifted -- they are
  missing entries this REAPER build has (e.g. "Add a range of notes into
  selection", and the snapping twin of "Stretch note positions
  (arpeggiate)"), and two rows are marked "Duplicate in docs?".

  There is no API to enumerate behaviors, but GetMouseModifier() returns
  the NAME of whatever is currently assigned. So we probe: for each
  behavior id, assign it, read the name back, and restore the original.
  An id REAPER doesn't know reads back as something other than what we
  set, which is how we find the end of each table.

  HOW TO RUN
    REAPER > Actions > Show action list > ReaScript: Load...
    pick this file, then run it. It writes:
      <REAPER resource path>/mouse_behaviors_dump.txt
    (Options > Show REAPER resource path in explorer/finder)

  SAFETY: every probe is restored immediately, and the whole run is
  wrapped in an undo block. Your mouse map is left exactly as it was.
]]

-- Contexts worth dumping. Add more as needed -- the probe is generic.
local CONTEXTS = {
  'MM_CTX_MIDI_NOTE',           -- MIDI note left drag
  'MM_CTX_MIDI_NOTE_CLK',       -- MIDI note left click
  'MM_CTX_MIDI_NOTE_DBLCLK',    -- MIDI note double click
  'MM_CTX_MIDI_NOTEEDGE',       -- MIDI note edge drag
  'MM_CTX_MIDI_PIANOROLL',      -- MIDI piano roll left drag
  'MM_CTX_MIDI_PIANOROLL_CLK',  -- MIDI piano roll left click
  'MM_CTX_MIDI_PIANOROLL_DBLCLK',
  'MM_CTX_MIDI_CCLANE',
  'MM_CTX_MIDI_CCEVT',
}

-- Probe ids 0..MAX_ID. REAPER's largest known table is well under this.
local MAX_ID = 80

-- Modifier slot 0 (no modifiers) is the one we borrow for probing.
local PROBE_SLOT = 0

local function name_of(ctx, slot)
  local ok, name = reaper.GetMouseModifier(ctx, slot, '')
  if type(ok) == 'string' then return ok end -- some bindings return the string directly
  return name or ''
end

local out = {}
local function emit(s) out[#out + 1] = s end

emit('REAPER mouse-modifier behavior tables')
emit('generated by reaper-input/scripts/dump_mouse_behaviors.lua')
emit('REAPER version: ' .. tostring(reaper.GetAppVersion()))
emit('')

reaper.Undo_BeginBlock()

for _, ctx in ipairs(CONTEXTS) do
  -- Save the slot we're about to trample.
  local saved = name_of(ctx, PROBE_SLOT)

  emit('[' .. ctx .. ']')
  local misses = 0
  for id = 0, MAX_ID do
    reaper.SetMouseModifier(ctx, PROBE_SLOT, tostring(id) .. ' m')
    local got = name_of(ctx, PROBE_SLOT)
    if got == nil or got == '' then
      misses = misses + 1
    else
      emit(string.format('%3d  %s', id, got))
      misses = 0
    end
    -- Eight consecutive dead ids means we're past the end of the table.
    if misses >= 8 then break end
  end

  -- Put it back exactly as we found it.
  reaper.SetMouseModifier(ctx, PROBE_SLOT, saved)
  emit('')
end

reaper.Undo_EndBlock('Dump mouse modifier behaviors (no-op)', -1)

local path = reaper.GetResourcePath() .. '/mouse_behaviors_dump.txt'
local f = io.open(path, 'w')
if f then
  f:write(table.concat(out, '\n'))
  f:close()
  reaper.ShowConsoleMsg('Wrote ' .. path .. '\n')
else
  -- Couldn't write: dump to the console so the run isn't wasted.
  reaper.ShowConsoleMsg(table.concat(out, '\n') .. '\n')
end
