[package]
name = "signal-proto"
description = "Signal protocol — domain types for rig control"
version.workspace = true
edition.workspace = true

[dependencies]
uuid = { version = "1.0", features = ["v4", "v5"] }
facet = { workspace = true, features = ["uuid"] }
daw-proto = { path = "../../daw/daw-proto" }

# -- Others
derive_aliases = "0.4"

[dev-dependencies]
facet-json = { workspace = true }

[lints]
workspace = true
