// This file has been generated by Specta. DO NOT EDIT.

import { createTauRPCProxy as createProxy, type InferCommandOutput } from 'taurpc'
type TAURI_CHANNEL<T> = (response: T) => void


export type ApiError = { code: number; message: string }

export type AppStatus = { counter_value: number; user_count: number; is_processing: boolean; last_message: string }

export type CounterError = { code: number; message: string }

export type CounterStats = { current_value: number; total_operations: number; last_operation: string }

export type ProcessingResult = { success: boolean; message: string; duration_ms: number }

export type TaskProgress = { task_id: string; progress: number; message: string }

export type User = { id: number; name: string; email: string; active: boolean }

export type UserApiError = { code: number; message: string }

export type UserStats = { total_users: number; active_users: number; last_created: string }

const ARGS_MAP = { '':'{"error_occurred":["error"],"get_status":[],"reset_app":[],"status_changed":["status"]}', 'counter':'{"add":["amount"],"decrement":[],"get_stats":[],"get_value":[],"increment":[],"multiply":["factor"],"reset":[],"set_value":["value"],"subtract":["amount"]}', 'tasks':'{"run_long_task":["task_name","duration_seconds","on_progress"],"simulate_batch_processing":["batch_size","on_progress"]}', 'users':'{"create_user":["name","email"],"delete_user":["user_id"],"get_all_users":[],"get_user_by_id":["id"],"get_user_stats":[],"toggle_user_status":["user_id"],"update_user":["id","name","email"]}' }
export type Router = { "": {error_occurred: (error: ApiError) => Promise<void>, 
get_status: () => Promise<AppStatus>, 
reset_app: () => Promise<string>, 
status_changed: (status: AppStatus) => Promise<void>},
"counter": {add: (amount: number) => Promise<number>, 
decrement: () => Promise<number>, 
get_stats: () => Promise<CounterStats>, 
get_value: () => Promise<number>, 
increment: () => Promise<number>, 
multiply: (factor: number) => Promise<number>, 
reset: () => Promise<number>, 
set_value: (value: number) => Promise<number>, 
subtract: (amount: number) => Promise<number>},
"tasks": {run_long_task: (taskName: string, durationSeconds: number, onProgress: TAURI_CHANNEL<TaskProgress>) => Promise<ProcessingResult>, 
simulate_batch_processing: (batchSize: number, onProgress: TAURI_CHANNEL<TaskProgress>) => Promise<ProcessingResult>},
"users": {create_user: (name: string, email: string) => Promise<User>, 
delete_user: (userId: number) => Promise<string>, 
get_all_users: () => Promise<User[]>, 
get_user_by_id: (id: number) => Promise<User>, 
get_user_stats: () => Promise<UserStats>, 
toggle_user_status: (userId: number) => Promise<User>, 
update_user: (id: number, name: string | null, email: string | null) => Promise<User>} };


export const createTauRPCProxy = () => createProxy<Router>(ARGS_MAP)
export type { InferCommandOutput }
