[package]
name = "task-cli"
version.workspace = true
edition.workspace = true

[[bin]]
name = "task"
path = "src/main.rs"

[dependencies]
vox = { workspace = true, features = ["transport-websocket", "transport-websocket-tls"] }
tokio = { workspace = true }
chrono.workspace = true
eyre.workspace = true
clap = { version = "4", features = ["derive", "env"] }
serde.workspace = true
serde_json.workspace = true
uuid.workspace = true
project-proto = { workspace = true }
