[package]
name = "task-cli"
version.workspace = true
edition.workspace = true

[[bin]]
name = "task"
path = "src/main.rs"

[dependencies]
task-core = { path = "../task-core" }
tokio = { workspace = true }
chrono.workspace = true
eyre.workspace = true
clap = { version = "4", features = ["derive", "env"] }
facet-json.workspace = true
