[package]
name = "signal"
version.workspace = true
edition.workspace = true
license.workspace = true
authors.workspace = true

[dependencies]
signal-controller = { path = "../signal-controller" }
signal-live = { path = "../signal-live" }
signal-proto = { path = "../signal-proto" }
signal-storage = { path = "../signal-storage" }
tokio.workspace = true
