//! Role-based download bundles.
//!
//! A download bundle is a curated set of files for a specific role
//! in an event or project. Each bundle generates a shareable link
//! (via Nextcloud public share) that gives the recipient one-click
//! access to everything they need.
//!
//! # Example
//!
//! ```text
//! downloads/
//! ├── bundles.md          ← bundle definitions
//! ├── orchestra-violin/   ← generated folder (shared via Nextcloud)
//! │   ├── Schedule.md
//! │   ├── Sheet Music/
//! │   │   ├── Song 1.pdf
//! │   │   └── Song 2.pdf
//! │   ├── Rehearsal Tracks/
//! │   │   ├── Song 1 - Click.mp3
//! │   │   └── Song 2 - Click.mp3
//! │   └── Stage Plot.pdf
//! └── orchestra-drums/    ← different bundle for drummer
//!     ├── Schedule.md
//!     ├── Drum Charts/
//!     └── Click Tracks/
//! ```
//!
//! The bundle folder can be auto-generated by collecting files from
//! the project based on the bundle definition, then shared via
//! Nextcloud's public share API.

use chrono::NaiveDate;
use facet::Facet;

/// All download bundles for an event/project.
/// Stored as `downloads/bundles.md`.
#[derive(Debug, Clone, PartialEq, Default, Facet)]
pub struct DownloadBundles {
    pub title: String,
    /// Parent event or project title.
    pub event: String,
    #[facet(default)]
    pub bundles: Vec<DownloadBundle>,
}

/// A single download bundle for a role or group.
#[derive(Debug, Clone, PartialEq, Default, Facet)]
pub struct DownloadBundle {
    /// Bundle identifier (e.g. "orchestra-violin", "band-drums", "crew-audio").
    pub id: String,
    /// Human-readable name (e.g. "Violin Section", "Drum Kit", "Audio Crew").
    pub name: String,
    /// Which role(s) this bundle is for.
    #[facet(default)]
    pub roles: Vec<String>,
    /// Which performance/act this belongs to (empty = event-wide).
    pub performance: Option<String>,

    // ── Content ──────────────────────────────────────────────────

    /// Files to include in the bundle.
    /// Paths are relative to the project root.
    #[facet(default)]
    pub files: Vec<BundleFile>,

    /// Auto-include rules: pull files matching patterns.
    #[facet(default)]
    pub include_rules: Vec<IncludeRule>,

    // ── Sharing ──────────────────────────────────────────────────

    /// Nextcloud share URL (generated when bundle is published).
    pub share_url: Option<String>,
    /// Nextcloud share token.
    pub share_token: Option<String>,
    /// Password protection for the share.
    pub password: Option<String>,
    /// Expiration date for the share link.
    pub expires: Option<NaiveDate>,
    /// Whether the bundle has been published (share link created).
    pub published: bool,

    // ── Tracking ─────────────────────────────────────────────────

    /// Who this bundle was sent to.
    #[facet(default)]
    pub recipients: Vec<Recipient>,

    #[facet(default)]
    pub notes: String,
}

/// A file included in a download bundle.
#[derive(Debug, Clone, PartialEq, Default, Facet)]
pub struct BundleFile {
    /// Source path relative to project root.
    pub source: String,
    /// Destination path within the bundle (can rename/reorganize).
    /// If empty, uses the source filename.
    pub dest: Option<String>,
    /// Category for organizing within the bundle.
    pub category: Option<String>,
}

/// Rule for auto-including files from the project.
#[derive(Debug, Clone, PartialEq, Default, Facet)]
pub struct IncludeRule {
    /// Glob pattern relative to project root (e.g. "scores/violin/*.pdf").
    pub pattern: String,
    /// Category to file them under in the bundle.
    pub category: Option<String>,
}

/// A person who received the bundle link.
#[derive(Debug, Clone, PartialEq, Default, Facet)]
pub struct Recipient {
    pub name: String,
    pub email: Option<String>,
    pub sent_date: Option<NaiveDate>,
    /// Whether they've accessed the link.
    pub accessed: bool,
    /// Whether they've downloaded the files.
    pub downloaded: bool,
}
