[package]
name = "fts-ui"
description = "FastTrack Studio design system"
version.workspace = true
edition.workspace = true

[dependencies]
dioxus = { workspace = true }
dioxus-primitives = { workspace = true }
lumen-blocks = { workspace = true }
lucide-dioxus = { workspace = true }
tracing = { workspace = true }

[lints]
workspace = true
