[package]
name = "fts-ui"
description = "FastTrack Studio design system"
version.workspace = true
edition.workspace = true

[dependencies]
chrono = "0.4"
clsx = { workspace = true }
dioxus = { workspace = true }
dioxus-primitives = { workspace = true }
lucide-dioxus = { workspace = true }
tracing = { workspace = true }
tw_merge = { workspace = true }

[lints]
workspace = true
